// Preguntas para los duelos 1v1. Son deliberadamente mucho más difíciles que
// las del día: acá no alcanza con seguir el fútbol, hay que saber datos viejos
// y específicos. Viven aparte del seed diario porque no se programan por fecha,
// se sortean cinco en cada duelo.
export const DUEL_POOL = [
  {
    question: "¿Quién fue el primer futbolista en ganar el Balón de Oro, en 1956?",
    option_a: "Alfredo Di Stéfano",
    option_b: "Stanley Matthews",
    option_c: "Raymond Kopa",
    option_d: "Ferenc Puskás",
    correct_answer: "b",
    difficulty: "ultra",
  },
  {
    question: "¿Qué club ganó la primera Copa Intercontinental, en 1960?",
    option_a: "Peñarol",
    option_b: "Santos",
    option_c: "Real Madrid",
    option_d: "Benfica",
    correct_answer: "c",
    difficulty: "dificil",
  },
  {
    question: "¿Cuántos goles convirtió Ferenc Puskás con la selección de Hungría?",
    option_a: "62",
    option_b: "71",
    option_c: "84",
    option_d: "95",
    correct_answer: "c",
    difficulty: "demonio",
  },
  {
    question: "¿Qué selección fue apodada 'El Equipo de Oro' en la década del 50?",
    option_a: "Austria",
    option_b: "Hungría",
    option_c: "Checoslovaquia",
    option_d: "Yugoslavia",
    correct_answer: "b",
    difficulty: "ultra",
  },
  {
    question: "¿Quién convirtió el primer gol en la historia de los Mundiales, en 1930?",
    option_a: "Lucien Laurent",
    option_b: "Guillermo Stábile",
    option_c: "Pedro Cea",
    option_d: "Bert Patenaude",
    correct_answer: "a",
    difficulty: "demonio",
  },
  {
    question: "¿En qué año se fundó la FIFA?",
    option_a: "1896",
    option_b: "1900",
    option_c: "1904",
    option_d: "1912",
    correct_answer: "c",
    difficulty: "dificil",
  },
  {
    question: "¿Quién fue el primer futbolista no europeo en ganar el Balón de Oro, en 1995?",
    option_a: "Romário",
    option_b: "George Weah",
    option_c: "Ronaldo Nazário",
    option_d: "Rivaldo",
    correct_answer: "b",
    difficulty: "ultra",
  },
  {
    question: "¿Qué club ganó más Copas Libertadores en toda la historia?",
    option_a: "Boca Juniors",
    option_b: "Peñarol",
    option_c: "Independiente",
    option_d: "River Plate",
    correct_answer: "c",
    difficulty: "dificil",
  },
  {
    question: "¿Cuántas Copas Libertadores ganó Independiente de Avellaneda?",
    option_a: "5",
    option_b: "6",
    option_c: "7",
    option_d: "8",
    correct_answer: "c",
    difficulty: "ultra",
  },
  {
    question: "¿Qué selección ganó la Eurocopa 1992 entrando de reemplazo por Yugoslavia?",
    option_a: "Suecia",
    option_b: "Dinamarca",
    option_c: "Noruega",
    option_d: "Escocia",
    correct_answer: "b",
    difficulty: "dificil",
  },
  {
    question: "¿Quién es el máximo goleador histórico de la Copa Libertadores?",
    option_a: "Alberto Spencer",
    option_b: "Fernando Morena",
    option_c: "Pelé",
    option_d: "Daniel Onega",
    correct_answer: "a",
    difficulty: "demonio",
  },
  {
    question: "¿Quién tiene el récord de más goles oficiales en un año calendario, con 91?",
    option_a: "Cristiano Ronaldo",
    option_b: "Gerd Müller",
    option_c: "Lionel Messi",
    option_d: "Pelé",
    correct_answer: "c",
    difficulty: "dificil",
  },
  {
    question: "¿Cuál fue la primera selección en ganar un Mundial fuera de su continente?",
    option_a: "Uruguay",
    option_b: "Brasil",
    option_c: "Italia",
    option_d: "Alemania",
    correct_answer: "b",
    difficulty: "ultra",
  },
  {
    question: "¿Qué club brasileño ganó la Copa Libertadores en 1962 y 1963 con Pelé en el plantel?",
    option_a: "Palmeiras",
    option_b: "Santos",
    option_c: "Flamengo",
    option_d: "Botafogo",
    correct_answer: "b",
    difficulty: "dificil",
  },
  {
    question: "¿Qué entrenador dirigió a los Países Bajos del 'Fútbol Total' en el Mundial 1974?",
    option_a: "Rinus Michels",
    option_b: "Ernst Happel",
    option_c: "Johan Cruyff",
    option_d: "Guus Hiddink",
    correct_answer: "a",
    difficulty: "dificil",
  },
  {
    question: "¿Qué club inglés ganó la Copa de Europa en 1979 y 1980?",
    option_a: "Aston Villa",
    option_b: "Liverpool",
    option_c: "Nottingham Forest",
    option_d: "Leeds United",
    correct_answer: "c",
    difficulty: "ultra",
  },
  {
    question: "¿Qué entrenador llevó al Nottingham Forest a ganar dos Copas de Europa seguidas?",
    option_a: "Bob Paisley",
    option_b: "Brian Clough",
    option_c: "Bill Shankly",
    option_d: "Don Revie",
    correct_answer: "b",
    difficulty: "demonio",
  },
  {
    question: "¿Qué selección ganó la primera Copa África, en 1957?",
    option_a: "Sudán",
    option_b: "Etiopía",
    option_c: "Egipto",
    option_d: "Sudáfrica",
    correct_answer: "c",
    difficulty: "demonio",
  },
  {
    question: "¿Quién fue el máximo goleador del Mundial de 1970?",
    option_a: "Pelé",
    option_b: "Gerd Müller",
    option_c: "Jairzinho",
    option_d: "Teófilo Cubillas",
    correct_answer: "b",
    difficulty: "ultra",
  },
  {
    question: "¿En qué año se disputó el primer partido internacional oficial de la historia?",
    option_a: "1863",
    option_b: "1872",
    option_c: "1885",
    option_d: "1890",
    correct_answer: "b",
    difficulty: "ultra",
  },
  {
    question: "¿Entre qué dos selecciones se jugó el primer partido internacional oficial?",
    option_a: "Inglaterra y Gales",
    option_b: "Escocia e Inglaterra",
    option_c: "Inglaterra e Irlanda",
    option_d: "Escocia y Gales",
    correct_answer: "b",
    difficulty: "ultra",
  },
  {
    question: "¿Qué club argentino ganó tres Copas Libertadores seguidas entre 1968 y 1970?",
    option_a: "Racing",
    option_b: "Independiente",
    option_c: "Estudiantes de La Plata",
    option_d: "Boca Juniors",
    correct_answer: "c",
    difficulty: "ultra",
  },
  {
    question: "¿Qué brasileño ganó el Mundial como jugador en 1958 y 1962, y como entrenador en 1970?",
    option_a: "Mario Zagallo",
    option_b: "Carlos Alberto Parreira",
    option_c: "Telê Santana",
    option_d: "Vicente Feola",
    correct_answer: "a",
    difficulty: "dificil",
  },
  {
    question: "¿En qué estadio se disputó la final del Mundial de 1966?",
    option_a: "Old Trafford",
    option_b: "Wembley",
    option_c: "Villa Park",
    option_d: "Goodison Park",
    correct_answer: "b",
    difficulty: "dificil",
  },
  {
    question: "¿Quién fue el máximo goleador del Mundial de 1978?",
    option_a: "Mario Kempes",
    option_b: "Rob Rensenbrink",
    option_c: "Teófilo Cubillas",
    option_d: "Leopoldo Luque",
    correct_answer: "a",
    difficulty: "dificil",
  },
  {
    question: "¿Cuántas Copas Libertadores ganó Boca Juniors?",
    option_a: "4",
    option_b: "5",
    option_c: "6",
    option_d: "7",
    correct_answer: "c",
    difficulty: "dificil",
  },
  {
    question: "¿Qué club uruguayo ganó cinco Copas Libertadores?",
    option_a: "Nacional",
    option_b: "Peñarol",
    option_c: "Defensor Sporting",
    option_d: "Danubio",
    correct_answer: "b",
    difficulty: "ultra",
  },
  {
    question: "¿Cuántas veces ganó Brasil la Copa América?",
    option_a: "7",
    option_b: "8",
    option_c: "9",
    option_d: "12",
    correct_answer: "c",
    difficulty: "ultra",
  },
  {
    question: "¿Quién fue el primer jugador en disputar cinco Mundiales?",
    option_a: "Antonio Carbajal",
    option_b: "Lothar Matthäus",
    option_c: "Gianluigi Buffon",
    option_d: "Rafael Márquez",
    correct_answer: "a",
    difficulty: "demonio",
  },
  {
    question: "¿Cuántas veces ganó Italia la Copa del Mundo?",
    option_a: "3",
    option_b: "4",
    option_c: "5",
    option_d: "2",
    correct_answer: "b",
    difficulty: "dificil",
  },
  {
    question: "¿Quién ganó el Balón de Oro en 1997?",
    option_a: "Zinedine Zidane",
    option_b: "Ronaldo Nazário",
    option_c: "Roberto Baggio",
    option_d: "Rivaldo",
    correct_answer: "b",
    difficulty: "dificil",
  },
  {
    question: "¿Qué selección ganó más veces la Copa Confederaciones?",
    option_a: "Francia",
    option_b: "Brasil",
    option_c: "Argentina",
    option_d: "Alemania",
    correct_answer: "b",
    difficulty: "dificil",
  },
  {
    question: "¿Cuántos partidos consecutivos de Premier League estuvo invicto el Arsenal entre 2003 y 2004?",
    option_a: "38",
    option_b: "42",
    option_c: "49",
    option_d: "55",
    correct_answer: "c",
    difficulty: "demonio",
  },
  {
    question: "¿Ante qué club convirtió Pelé su gol número 1000?",
    option_a: "Flamengo",
    option_b: "Vasco da Gama",
    option_c: "Corinthians",
    option_d: "Botafogo",
    correct_answer: "b",
    difficulty: "demonio",
  },
  {
    question: "¿Qué club ganó la primera edición de la Copa de la UEFA, en 1972?",
    option_a: "Tottenham",
    option_b: "Liverpool",
    option_c: "Juventus",
    option_d: "Feyenoord",
    correct_answer: "a",
    difficulty: "demonio",
  },
  {
    question: "¿Cuántos goles hizo Gerd Müller en la Bundesliga en la temporada 1971-72?",
    option_a: "36",
    option_b: "38",
    option_c: "40",
    option_d: "44",
    correct_answer: "c",
    difficulty: "demonio",
  },
  {
    question: "¿Quién rompió el récord de goles de Gerd Müller en una temporada de Bundesliga?",
    option_a: "Robert Lewandowski",
    option_b: "Erling Haaland",
    option_c: "Miroslav Klose",
    option_d: "Mario Gómez",
    correct_answer: "a",
    difficulty: "ultra",
  },
  {
    question: "¿Qué club ganó la primera edición de la Copa Sudamericana, en 2002?",
    option_a: "San Lorenzo",
    option_b: "Cienciano",
    option_c: "Boca Juniors",
    option_d: "River Plate",
    correct_answer: "a",
    difficulty: "demonio",
  },
  {
    question: "¿Qué selección ganó la Copa América 1993, su último título antes de 2021?",
    option_a: "Brasil",
    option_b: "Uruguay",
    option_c: "Argentina",
    option_d: "Colombia",
    correct_answer: "c",
    difficulty: "ultra",
  },
  {
    question: "¿Cuántos arqueros ganaron el Balón de Oro en toda la historia del premio?",
    option_a: "Ninguno",
    option_b: "Uno",
    option_c: "Dos",
    option_d: "Tres",
    correct_answer: "b",
    difficulty: "demonio",
  },
  {
    question: "¿Cuál fue el primer club en ganar la Copa Libertadores y la Intercontinental el mismo año?",
    option_a: "Santos",
    option_b: "Peñarol",
    option_c: "Independiente",
    option_d: "Racing",
    correct_answer: "b",
    difficulty: "demonio",
  },
  {
    question: "¿Cuántos Mundiales consecutivos disputó Lothar Matthäus?",
    option_a: "3",
    option_b: "4",
    option_c: "5",
    option_d: "6",
    correct_answer: "c",
    difficulty: "demonio",
  },
  {
    question: "¿En qué año se abrió el Balón de Oro a futbolistas no europeos que jugaran en Europa?",
    option_a: "1990",
    option_b: "1995",
    option_c: "2000",
    option_d: "2007",
    correct_answer: "b",
    difficulty: "demonio",
  },
  {
    question: "¿Qué selección tiene el récord de más partidos internacionales consecutivos sin perder?",
    option_a: "Brasil",
    option_b: "España",
    option_c: "Italia",
    option_d: "Argentina",
    correct_answer: "c",
    difficulty: "demonio",
  },
  {
    question: "¿Cuántas finales de Champions League o Copa de Europa perdió la Juventus?",
    option_a: "5",
    option_b: "6",
    option_c: "7",
    option_d: "8",
    correct_answer: "c",
    difficulty: "demonio",
  },
  {
    question: "¿Qué club ganó la Recopa de Europa en 1961, su primera edición?",
    option_a: "Fiorentina",
    option_b: "Atlético de Madrid",
    option_c: "Rangers",
    option_d: "Tottenham",
    correct_answer: "a",
    difficulty: "demonio",
  },
  {
    question: "¿Qué entrenador ganó la Copa de Europa con Ajax y con Hamburgo?",
    option_a: "Rinus Michels",
    option_b: "Ernst Happel",
    option_c: "Stefan Kovács",
    option_d: "Udo Lattek",
    correct_answer: "b",
    difficulty: "demonio",
  },
  {
    question: "¿Quién ganó la Bota de Oro europea en la temporada 2018-19?",
    option_a: "Kylian Mbappé",
    option_b: "Lionel Messi",
    option_c: "Fabio Quagliarella",
    option_d: "Robert Lewandowski",
    correct_answer: "b",
    difficulty: "ultra",
  },
  {
    question: "¿Qué selección eliminó a Brasil en los cuartos de final del Mundial 2006?",
    option_a: "Francia",
    option_b: "Italia",
    option_c: "Portugal",
    option_d: "Alemania",
    correct_answer: "a",
    difficulty: "ultra",
  },
  {
    question: "¿Qué club mexicano llegó a la final de la Copa Libertadores 2001?",
    option_a: "América",
    option_b: "Cruz Azul",
    option_c: "Guadalajara",
    option_d: "Pumas",
    correct_answer: "b",
    difficulty: "demonio",
  },
];
