import "dotenv/config";
import { db, initSchema } from "./client.js";

function dateOffset(days) {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}

// Slot 1: trivia general de fútbol mundial
const SLOT1_POOL = [
  {
    question: "¿Quién es el máximo goleador histórico en la historia de los Mundiales de fútbol?",
    category: "Individuales",
    difficulty: "dificil",
    option_a: "Ronaldo Nazário",
    option_b: "Just Fontaine",
    option_c: "Miroslav Klose",
    option_d: "Gerd Müller",
    correct_answer: "c",
  },
  {
    question: "¿Qué selección ganó el primer Mundial de fútbol de la historia, disputado en 1930?",
    category: "Mundiales",
    difficulty: "media",
    option_a: "Argentina",
    option_b: "Uruguay",
    option_c: "Brasil",
    option_d: "Italia",
    correct_answer: "b",
  },
  {
    question: "¿Qué arquero es el único portero en la historia en ganar el Balón de Oro, en 1963?",
    category: "Individuales",
    difficulty: "dificil",
    option_a: "Gordon Banks",
    option_b: "Dino Zoff",
    option_c: "Gianluigi Buffon",
    option_d: "Lev Yashin",
    correct_answer: "d",
  },
  {
    question: "¿Qué club ganó la primera edición de la Copa Libertadores, en 1960?",
    category: "Libertadores",
    difficulty: "dificil",
    option_a: "River Plate",
    option_b: "Nacional",
    option_c: "Peñarol",
    option_d: "Olimpia",
    correct_answer: "c",
  },
  {
    question: "¿Quién tiene el récord de más goles en una sola edición de un Mundial, con 13 goles en 1958?",
    category: "Mundiales",
    difficulty: "dificil",
    option_a: "Pelé",
    option_b: "Just Fontaine",
    option_c: "Sándor Kocsis",
    option_d: "Eusébio",
    correct_answer: "b",
  },
  {
    question: "¿Qué selección ganó la primera edición de la Eurocopa, en 1960?",
    category: "Eurocopa",
    difficulty: "dificil",
    option_a: "Unión Soviética",
    option_b: "Yugoslavia",
    option_c: "Checoslovaquia",
    option_d: "Francia",
    correct_answer: "a",
  },
  {
    question: "¿En qué país se disputó el Mundial de 1970, donde Brasil ganó su tercer título?",
    category: "Mundiales",
    difficulty: "media",
    option_a: "Chile",
    option_b: "Argentina",
    option_c: "México",
    option_d: "Alemania",
    correct_answer: "c",
  },
  {
    question: "¿Quién fue el máximo goleador del Mundial de Brasil 2014, con 6 goles?",
    category: "Mundiales",
    difficulty: "dificil",
    option_a: "Lionel Messi",
    option_b: "Thomas Müller",
    option_c: "Neymar",
    option_d: "James Rodríguez",
    correct_answer: "d",
  },
  {
    question: "¿Qué selección se convirtió en 2022 en la primera de África en llegar a una semifinal de un Mundial?",
    category: "Mundiales",
    difficulty: "media",
    option_a: "Ghana",
    option_b: "Marruecos",
    option_c: "Senegal",
    option_d: "Camerún",
    correct_answer: "b",
  },
  {
    question: "¿Qué jugador tiene el récord de más partidos disputados en la historia de los Mundiales?",
    category: "Individuales",
    difficulty: "dificil",
    option_a: "Lothar Matthäus",
    option_b: "Diego Maradona",
    option_c: "Lionel Messi",
    option_d: "Franz Beckenbauer",
    correct_answer: "c",
  },
  {
    question: "¿Qué selección ganó el Mundial de 1950 al vencer a Brasil como local, en el histórico 'Maracanazo'?",
    category: "Mundiales",
    difficulty: "dificil",
    option_a: "Argentina",
    option_b: "Uruguay",
    option_c: "Paraguay",
    option_d: "Chile",
    correct_answer: "b",
  },
  {
    question: "¿En qué edición del Mundial se utilizó por primera vez el VAR (videoarbitraje)?",
    category: "Reglas",
    difficulty: "media",
    option_a: "Brasil 2014",
    option_b: "Rusia 2018",
    option_c: "Catar 2022",
    option_d: "Sudáfrica 2010",
    correct_answer: "b",
  },
  {
    question: "¿Qué arquero ganó el primer Guante de Oro al mejor portero de un Mundial, en 1994?",
    category: "Individuales",
    difficulty: "dificil",
    option_a: "Michel Preud'homme",
    option_b: "Fabien Barthez",
    option_c: "Óscar Córdoba",
    option_d: "Jorge Campos",
    correct_answer: "a",
  },
  {
    question: "¿Cuál fue el resultado final del partido decisivo del Mundial 1950 entre Uruguay y Brasil?",
    category: "Mundiales",
    difficulty: "dificil",
    option_a: "Uruguay 2 - Brasil 1",
    option_b: "Uruguay 3 - Brasil 2",
    option_c: "Uruguay 1 - Brasil 0",
    option_d: "Uruguay 2 - Brasil 0",
    correct_answer: "a",
  },
  {
    question: "¿Qué jugador convirtió el gol más rápido en la historia de los Mundiales (10,8 segundos), en 2002?",
    category: "Mundiales",
    difficulty: "dificil",
    option_a: "Ronaldo Nazário",
    option_b: "Hakan Şükür",
    option_c: "Miroslav Klose",
    option_d: "Michael Owen",
    correct_answer: "b",
  },
  {
    question: "¿Qué selección ganó la primera Copa Rey Fahd en 1992, antecesora de la Copa Confederaciones?",
    category: "Historia",
    difficulty: "dificil",
    option_a: "Brasil",
    option_b: "Alemania",
    option_c: "Argentina",
    option_d: "México",
    correct_answer: "c",
  },
  {
    question: "¿Qué dos países coorganizaron el Mundial de 2002, el primero disputado en Asia?",
    category: "Mundiales",
    difficulty: "media",
    option_a: "China y Japón",
    option_b: "Japón y Corea del Sur",
    option_c: "Tailandia y Corea del Sur",
    option_d: "Corea del Sur y China",
    correct_answer: "b",
  },
  {
    question: "¿Cuántos goles convirtió Pelé en total a lo largo de los Mundiales que disputó?",
    category: "Individuales",
    difficulty: "dificil",
    option_a: "10",
    option_b: "12",
    option_c: "15",
    option_d: "9",
    correct_answer: "b",
  },
  {
    question: "¿Qué selección ganó el Mundial de 1974, disputado en Alemania?",
    category: "Mundiales",
    difficulty: "media",
    option_a: "Países Bajos",
    option_b: "Alemania Occidental",
    option_c: "Polonia",
    option_d: "Brasil",
    correct_answer: "b",
  },
  {
    question: "¿Qué jugador convirtió, en el mismo partido de cuartos de final del Mundial 1986, el gol de 'la Mano de Dios' y el 'Gol del Siglo'?",
    category: "Individuales",
    difficulty: "media",
    option_a: "Jorge Valdano",
    option_b: "Diego Maradona",
    option_c: "Jorge Burruchaga",
    option_d: "Claudio Caniggia",
    correct_answer: "b",
  },
];

// Slot 2: liga chilena, con foco en Universidad de Chile
const SLOT2_POOL = [
  {
    question: "¿En qué año se fundó Universidad de Chile, el club conocido como 'La U'?",
    category: "Liga Chilena",
    difficulty: "dificil",
    option_a: "1925",
    option_b: "1927",
    option_c: "1933",
    option_d: "1910",
    correct_answer: "b",
  },
  {
    question: "¿Qué título internacional ganó Universidad de Chile en 2011, el primero de su historia?",
    category: "Liga Chilena",
    difficulty: "dificil",
    option_a: "Copa Libertadores",
    option_b: "Recopa Sudamericana",
    option_c: "Copa Sudamericana",
    option_d: "Copa Merconorte",
    correct_answer: "c",
  },
  {
    question: "¿Qué entrenador argentino dirigió a Universidad de Chile durante su histórica campaña de 2011?",
    category: "Liga Chilena",
    difficulty: "dificil",
    option_a: "Marcelo Bielsa",
    option_b: "Jorge Sampaoli",
    option_c: "Gerardo Martino",
    option_d: "Marcelo Gallardo",
    correct_answer: "b",
  },
  {
    question: "¿Cómo se conoce al clásico entre Universidad de Chile y Universidad Católica?",
    category: "Liga Chilena",
    difficulty: "media",
    option_a: "Superclásico",
    option_b: "Clásico del Sur",
    option_c: "Clásico Universitario",
    option_d: "Clásico Capitalino",
    correct_answer: "c",
  },
  {
    question: "¿Cómo se conoce al clásico entre Colo-Colo y Universidad de Chile, el más popular del fútbol chileno?",
    category: "Liga Chilena",
    difficulty: "media",
    option_a: "Clásico Universitario",
    option_b: "Superclásico",
    option_c: "Clásico del Pacífico",
    option_d: "Gran Clásico",
    correct_answer: "b",
  },
  {
    question: "¿Con qué apodo se conoció al histórico equipo de Universidad de Chile campeón en la década de 1960?",
    category: "Liga Chilena",
    difficulty: "dificil",
    option_a: "El Ballet Azul",
    option_b: "La Máquina Azul",
    option_c: "Los Azules de Oro",
    option_d: "El Escuadrón Azul",
    correct_answer: "a",
  },
  {
    question: "¿Ante qué equipo argentino perdió Universidad de Chile la final de la Copa Libertadores de 1970?",
    category: "Liga Chilena",
    difficulty: "dificil",
    option_a: "Boca Juniors",
    option_b: "River Plate",
    option_c: "Estudiantes de La Plata",
    option_d: "Racing Club",
    correct_answer: "c",
  },
  {
    question: "¿En qué club chileno se formó y debutó profesionalmente Marcelo Salas antes de partir al fútbol internacional?",
    category: "Liga Chilena",
    difficulty: "media",
    option_a: "Colo-Colo",
    option_b: "Universidad de Chile",
    option_c: "Universidad Católica",
    option_d: "Cobreloa",
    correct_answer: "b",
  },
  {
    question: "¿Qué club chileno tiene más títulos de Primera División en la historia?",
    category: "Liga Chilena",
    difficulty: "media",
    option_a: "Universidad de Chile",
    option_b: "Universidad Católica",
    option_c: "Colo-Colo",
    option_d: "Cobreloa",
    correct_answer: "c",
  },
  {
    question: "¿Qué club chileno ganó la Copa Libertadores en 1991, siendo hasta hoy el único club de Chile en lograrlo?",
    category: "Liga Chilena",
    difficulty: "dificil",
    option_a: "Universidad de Chile",
    option_b: "Colo-Colo",
    option_c: "Universidad Católica",
    option_d: "Palestino",
    correct_answer: "b",
  },
  {
    question: "¿Qué jugador fundó el club Colo-Colo en 1925?",
    category: "Liga Chilena",
    difficulty: "dificil",
    option_a: "David Arellano",
    option_b: "Carlos Caszely",
    option_c: "Elías Figueroa",
    option_d: "Francisco Valdés",
    correct_answer: "a",
  },
  {
    question: "¿Qué club del norte de Chile llegó a dos finales consecutivas de la Copa Libertadores (1981 y 1982) sin poder consagrarse campeón?",
    category: "Liga Chilena",
    difficulty: "dificil",
    option_a: "Cobresal",
    option_b: "Deportes Antofagasta",
    option_c: "Cobreloa",
    option_d: "Deportes Iquique",
    correct_answer: "c",
  },
  {
    question: "¿En qué año Chile fue sede de la Copa del Mundo?",
    category: "Liga Chilena",
    difficulty: "media",
    option_a: "1958",
    option_b: "1962",
    option_c: "1966",
    option_d: "1970",
    correct_answer: "b",
  },
  {
    question: "¿Qué apodo recibe históricamente Universidad de Chile por sus destacadas giras internacionales?",
    category: "Liga Chilena",
    difficulty: "dificil",
    option_a: "El Romántico Viajero",
    option_b: "El Trotamundos Azul",
    option_c: "El Viajero Universitario",
    option_d: "El Nómade Azul",
    correct_answer: "a",
  },
  {
    question: "¿A qué selección venció Chile en la final de la Copa América 2015, disputada en su propio país, para ganar su primer título continental?",
    category: "Liga Chilena",
    difficulty: "media",
    option_a: "Brasil",
    option_b: "Uruguay",
    option_c: "Argentina",
    option_d: "Perú",
    correct_answer: "c",
  },
  {
    question: "¿Qué equipo enfrentó y venció Universidad de Chile en la final de la Copa Sudamericana 2011?",
    category: "Liga Chilena",
    difficulty: "dificil",
    option_a: "LDU Quito",
    option_b: "Independiente del Valle",
    option_c: "Emelec",
    option_d: "Barcelona SC",
    correct_answer: "a",
  },
  {
    question: "¿En qué estadio chileno se disputan tradicionalmente las grandes finales del fútbol nacional y los partidos de la selección?",
    category: "Liga Chilena",
    difficulty: "media",
    option_a: "Estadio Monumental",
    option_b: "Estadio Nacional",
    option_c: "Estadio Sausalito",
    option_d: "Estadio El Teniente",
    correct_answer: "b",
  },
  {
    question: "¿Cuántos títulos oficiales ganó Universidad de Chile durante su histórica temporada 2011 (Apertura, Copa Sudamericana y Clausura)?",
    category: "Liga Chilena",
    difficulty: "dificil",
    option_a: "2",
    option_b: "3",
    option_c: "4",
    option_d: "1",
    correct_answer: "b",
  },
  {
    question: "¿Quién fue el primer técnico de la selección chilena en ganar un título oficial en el fútbol profesional?",
    category: "Liga Chilena",
    difficulty: "media",
    option_a: "Marcelo Bielsa",
    option_b: "Jorge Sampaoli",
    option_c: "Gerardo Martino",
    option_d: "Ernesto Figueroa",
    correct_answer: "b",
  },
  {
    question: "¿Qué club chileno ha ganado más Copas Sudamericanas?",
    category: "Liga Chilena",
    difficulty: "dificil",
    option_a: "Universidad de Chile",
    option_b: "Colo-Colo",
    option_c: "Universidad Católica",
    option_d: "Palestino",
    correct_answer: "a",
  },
];

// Slot 3: fútbol europeo, MUCHO más difícil (Champions, detalles muy específicos)
const SLOT3_POOL = [
  {
    question: "¿Quién ganó la Champions League 2007?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "Liverpool",
    option_b: "Chelsea",
    option_c: "AC Milan",
    option_d: "Bayern Múnich",
    correct_answer: "c",
  },
  {
    question: "¿Qué equipo ganó la Champions League 2006?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "AC Milan",
    option_b: "Barcelona",
    option_c: "Arsenal",
    option_d: "Liverpool",
    correct_answer: "a",
  },
  {
    question: "¿Quién ganó la Champions League 2005?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "Bayern Múnich",
    option_b: "Liverpool",
    option_c: "Chelsea",
    option_d: "Valencia",
    correct_answer: "b",
  },
  {
    question: "¿Qué equipo ganó la Champions League 2008?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "Manchester United",
    option_b: "Real Madrid",
    option_c: "Barcelona",
    option_d: "Chelsea",
    correct_answer: "a",
  },
  {
    question: "¿Quién fue goleador de la Champions League 2007-08 con 12 goles?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "Cristiano Ronaldo",
    option_b: "Lionel Messi",
    option_c: "Eidur Gudjohnsen",
    option_d: "Didier Drogba",
    correct_answer: "a",
  },
  {
    question: "¿Qué club ganó 6 Champions League entre 1956 y 1960?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "Barcelona",
    option_b: "Real Madrid",
    option_c: "Benfica",
    option_d: "AC Milan",
    correct_answer: "b",
  },
  {
    question: "¿En qué año se disputó la mayor remontada de Champions: Barcelona 6-1 PSG?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "2015",
    option_b: "2016",
    option_c: "2017",
    option_d: "2014",
    correct_answer: "b",
  },
  {
    question: "¿Quién fue máximo goleador histórico de Champions hasta 2017?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "Lionel Messi",
    option_b: "Cristiano Ronaldo",
    option_c: "Raúl González",
    option_d: "Alfredo Di Stéfano",
    correct_answer: "b",
  },
  {
    question: "¿Qué equipo fue el primer tricampeón de Champions consecutivas en la era moderna?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "Bayern Múnich",
    option_b: "AC Milan",
    option_c: "Real Madrid",
    option_d: "Liverpool",
    correct_answer: "a",
  },
  {
    question: "¿Quién ganó la Champions League 2000?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "Real Madrid",
    option_b: "Bayern Múnich",
    option_c: "Valencia",
    option_d: "Juventus",
    correct_answer: "a",
  },
  {
    question: "¿En qué ciudad se disputó la final de Champions 1999 donde Manchester United remontó en los últimos minutos?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "Estambul",
    option_b: "Barcelona",
    option_c: "Róterdam",
    option_d: "Estocolmo",
    correct_answer: "a",
  },
  {
    question: "¿Qué equipo ganó la Copa de Europa 1980 ganando desde fuera del campo?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "Liverpool",
    option_b: "Nottingham Forest",
    option_c: "Aston Villa",
    option_d: "Bayern Múnich",
    correct_answer: "a",
  },
  {
    question: "¿Cuántos títulos de Champions tiene Real Madrid hasta 2024?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "13",
    option_b: "14",
    option_c: "15",
    option_d: "12",
    correct_answer: "c",
  },
  {
    question: "¿Quién ganó la Champions League 2001?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "AC Milan",
    option_b: "Bayern Múnich",
    option_c: "Juventus",
    option_d: "Valencia",
    correct_answer: "a",
  },
  {
    question: "¿Qué equipo fue el primero en ganar la Champions League con entrenador español desde el siglo XX?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "Barcelona",
    option_b: "Real Madrid",
    option_c: "Villarreal",
    option_d: "Atlético Madrid",
    correct_answer: "a",
  },
  {
    question: "¿En qué año Barcelona ganó su primer Champions League?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "1990",
    option_b: "1992",
    option_c: "1994",
    option_d: "1996",
    correct_answer: "b",
  },
  {
    question: "¿Quién ganó la Champions League 2002?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "Bayern Múnich",
    option_b: "Real Madrid",
    option_c: "Valencia",
    option_d: "Juventus",
    correct_answer: "b",
  },
  {
    question: "¿Qué equipo inglés ganó la Champions League 2019?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "Manchester City",
    option_b: "Liverpool",
    option_c: "Manchester United",
    option_d: "Chelsea",
    correct_answer: "b",
  },
  {
    question: "¿Cuántos balones de oro ganó Messi jugando en Europa?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "6",
    option_b: "7",
    option_c: "8",
    option_d: "5",
    correct_answer: "c",
  },
  {
    question: "¿Qué equipo ganó la Champions League 2003?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "AC Milan",
    option_b: "Juventus",
    option_c: "Valencia",
    option_d: "Real Madrid",
    correct_answer: "a",
  },
];

// Modo B: Pool de "¿Quién es más...?"
const QUIEN_ES_MAS_POOL = [
  "¿Quién es más probable que haga el ridículo en una final?",
  "¿Quién es más probable que discuta con el árbitro a través de la tele?",
  "¿Quién es más probable que se despierte a las 4am para ver un partido?",
  "¿Quién es más probable que apueste su sueldo entero a un partido?",
  "¿Quién es más probable que tenga la camiseta más cara del grupo?",
  "¿Quién es más probable que se cambie de hincha por conveniencia?",
  "¿Quién es más probable que se acuerde de un resultado de hace 20 años?",
  "¿Quién es más probable que llore si su equipo pierde una final?",
  "¿Quién es más probable que llegue tarde a ver un partido?",
  "¿Quién es más probable que discuta de fútbol hasta las 3 de la mañana?",
  "¿Quién es más probable que se pierda el gol importante por estar en el baño?",
  "¿Quién es más probable que hable de fútbol hasta en un casamiento?",
  "¿Quién es más probable que se olvide de responder el trivia de hoy?",
  "¿Quién es más probable que festeje un gol solo en su casa como si estuviera en la cancha?",
  "¿Quién es más probable que diga 'yo lo hubiera atajado'?",
  "¿Quién es más probable que compre una camiseta y nunca se la ponga?",
  "¿Quién es más probable que se pelee por un gol en el picadito del domingo?",
  "¿Quién es más probable que se sepa la alineación completa de memoria?",
  "¿Quién es más probable que falle la pregunta de hoy?",
  "¿Quién es más probable que llame llorando después de una derrota?",
];

// Modo B: Pool de "¿Qué prefieres...?"
const QUE_PREFIERES_POOL = [
  "¿Qué prefieres: que tu equipo pierda 5-0 en casa o 1-0 de visitante?",
  "¿Qué prefieres: tener un goleador inconsistente o un portero que falla a veces?",
  "¿Qué prefieres: ver un partido aburrido 1-0 o un 4-4 caótico?",
  "¿Qué prefieres: que se suspenda tu partido favorito o que lo gane el rival?",
  "¿Qué prefieres: perder una final o perder al mejor jugador antes del torneo?",
  "¿Qué prefieres: un arbitraje que te beneficie o uno que sea justo?",
  "¿Qué prefieres: un equipo joven y prometedor o uno veterano ganador?",
  "¿Qué prefieres: el ataque espectacular o la defensa de acero?",
  "¿Qué prefieres: una goleada en tu contra o perder 1-0 en los últimos segundos?",
  "¿Qué prefieres: ver a tu equipo perder o no poder verlo jugar?",
  "¿Qué prefieres: ser campeón aburrido o subcampeón emocionante?",
  "¿Qué prefieres: un técnico exigente o uno permisivo?",
  "¿Qué prefieres: muchos partidos aburridos o pocos partidos espectaculares?",
  "¿Qué prefieres: un equipo local malo o uno extranjero ganador?",
  "¿Qué prefieres: un gol de suerte o uno hermoso de tu rival?",
  "¿Qué prefieres: ganar de forma fea o perder de forma hermosa?",
  "¿Qué prefieres: un fichaje star o un equipo equilibrado?",
  "¿Qué prefieres: jugar siempre o entrenar bajo presión?",
  "¿Qué prefieres: un rival clásico o uno impredecible?",
  "¿Qué prefieres: empatada controvertida o derrota justa?",
];

// Personalidades por liga (se elegirá una al azar cada día)
const PERSONALITY_TEMPLATES = [
  {
    prompt: "Si {name} fuera a la cárcel, ¿por qué sería?",
    options: [
      "Por abusar de cebollitas al pedir gol",
      "Por arruinar predicciones con análisis",
      "Por festejar goles como si ganara Libertadores",
      "Por llevar 10 camisetas al partido",
    ],
  },
  {
    prompt: "Si {name} fuera entrenador, ¿cuál sería su estrategia?",
    options: [
      "Todos atacan aunque pierdan 5-0",
      "Todos defienden aunque ganen",
      "Tácticas que solo funcionan en teoría",
      "Cambios cada 5 minutos sin razón",
    ],
  },
  {
    prompt: "Si {name} fuera árbitro, ¿qué pasaría?",
    options: [
      "Expulsaría a quien le reclame",
      "Solo pitaría si come cebollitas",
      "Haría más goles que los jugadores",
      "Se dormiría durante el partido",
    ],
  },
  {
    prompt: "Si {name} ganara la Libertadores, ¿qué haría?",
    options: [
      "Lloraría por 3 días seguidos",
      "Cambiaría su apellido al del club",
      "Se tatúaría la copa en la frente",
      "Renunciaría al fútbol de puro feliz",
    ],
  },
  {
    prompt: "Si {name} fuera comentarista, ¿qué diría?",
    options: [
      "Opiniones controversiales cada 5 segundos",
      "Comparaciones con partidos hace 30 años",
      "Gritos que despertarían al barrio",
      "Análisis que nadie entiende",
    ],
  },
];

const NUM_DAYS = 20;

async function upsertQuestion(q, scheduled_date, slot) {
  const updateResult = await db.execute({
    sql: `UPDATE questions SET
            question = ?, category = ?, difficulty = ?,
            option_a = ?, option_b = ?, option_c = ?, option_d = ?, correct_answer = ?
          WHERE scheduled_date = ? AND slot = ?`,
    args: [
      q.question,
      q.category,
      q.difficulty,
      q.option_a,
      q.option_b,
      q.option_c,
      q.option_d,
      q.correct_answer,
      scheduled_date,
      slot,
    ],
  });

  if (updateResult.rowsAffected === 0) {
    await db.execute({
      sql: `INSERT INTO questions
        (question, category, difficulty, option_a, option_b, option_c, option_d, correct_answer, scheduled_date, slot)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      args: [
        q.question,
        q.category,
        q.difficulty,
        q.option_a,
        q.option_b,
        q.option_c,
        q.option_d,
        q.correct_answer,
        scheduled_date,
        slot,
      ],
    });
  }
}

async function upsertSpecialQuestion(type, prompt, scheduled_date) {
  const updateResult = await db.execute({
    sql: "UPDATE special_questions SET prompt = ? WHERE type = ? AND scheduled_date = ?",
    args: [prompt, type, scheduled_date],
  });

  if (updateResult.rowsAffected === 0) {
    await db.execute({
      sql: "INSERT INTO special_questions (type, prompt, scheduled_date) VALUES (?, ?, ?)",
      args: [type, prompt, scheduled_date],
    });
  }
}

async function seed() {
  await initSchema();

  for (let day = 0; day < NUM_DAYS; day++) {
    const scheduled_date = dateOffset(day);

    // Modo A: trivia normal
    await upsertQuestion(SLOT1_POOL[day % SLOT1_POOL.length], scheduled_date, 1);
    await upsertQuestion(SLOT2_POOL[day % SLOT2_POOL.length], scheduled_date, 2);
    await upsertQuestion(SLOT3_POOL[day % SLOT3_POOL.length], scheduled_date, 3);

    // Modo B: preguntas especiales
    await upsertSpecialQuestion("quien_es_mas", QUIEN_ES_MAS_POOL[day % QUIEN_ES_MAS_POOL.length], scheduled_date);
    await upsertSpecialQuestion("que_prefieres", QUE_PREFIERES_POOL[day % QUE_PREFIERES_POOL.length], scheduled_date);
  }

  console.log(
    `Seed completado: ${NUM_DAYS} días x 3 preguntas trivia (Modo A) + 2 preguntas especiales (Modo B).`
  );
  console.log(`Modo A: General / Liga Chilena / Europa (Aumentada dificultad)`);
  console.log(`Modo B: ¿Quién es más? / ¿Qué prefieres? / Pregunta personalizada (por liga)`);
  process.exit(0);
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
