import "dotenv/config";
import { db, initSchema } from "./client.js";

function dateOffset(days) {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}

// Slot 1: trivia general de fútbol mundial
const SLOT1_POOL = [
  {
    question: "¿Quién es el máximo goleador histórico en la historia de los Mundiales de fútbol?",
    category: "Individuales",
    difficulty: "dificil",
    option_a: "Ronaldo Nazário",
    option_b: "Just Fontaine",
    option_c: "Miroslav Klose",
    option_d: "Gerd Müller",
    correct_answer: "c",
  },
  {
    question: "¿Qué selección ganó el primer Mundial de fútbol de la historia, disputado en 1930?",
    category: "Mundiales",
    difficulty: "media",
    option_a: "Argentina",
    option_b: "Uruguay",
    option_c: "Brasil",
    option_d: "Italia",
    correct_answer: "b",
  },
  {
    question: "¿Qué arquero es el único portero en la historia en ganar el Balón de Oro, en 1963?",
    category: "Individuales",
    difficulty: "dificil",
    option_a: "Gordon Banks",
    option_b: "Dino Zoff",
    option_c: "Gianluigi Buffon",
    option_d: "Lev Yashin",
    correct_answer: "d",
  },
  {
    question: "¿Qué club ganó la primera edición de la Copa Libertadores, en 1960?",
    category: "Libertadores",
    difficulty: "dificil",
    option_a: "River Plate",
    option_b: "Nacional",
    option_c: "Peñarol",
    option_d: "Olimpia",
    correct_answer: "c",
  },
  {
    question: "¿Quién tiene el récord de más goles en una sola edición de un Mundial, con 13 goles en 1958?",
    category: "Mundiales",
    difficulty: "dificil",
    option_a: "Pelé",
    option_b: "Just Fontaine",
    option_c: "Sándor Kocsis",
    option_d: "Eusébio",
    correct_answer: "b",
  },
  {
    question: "¿Qué selección ganó la primera edición de la Eurocopa, en 1960?",
    category: "Eurocopa",
    difficulty: "dificil",
    option_a: "Unión Soviética",
    option_b: "Yugoslavia",
    option_c: "Checoslovaquia",
    option_d: "Francia",
    correct_answer: "a",
  },
  {
    question: "¿En qué país se disputó el Mundial de 1970, donde Brasil ganó su tercer título?",
    category: "Mundiales",
    difficulty: "media",
    option_a: "Chile",
    option_b: "Argentina",
    option_c: "México",
    option_d: "Alemania",
    correct_answer: "c",
  },
  {
    question: "¿Quién fue el máximo goleador del Mundial de Brasil 2014, con 6 goles?",
    category: "Mundiales",
    difficulty: "dificil",
    option_a: "Lionel Messi",
    option_b: "Thomas Müller",
    option_c: "Neymar",
    option_d: "James Rodríguez",
    correct_answer: "d",
  },
  {
    question: "¿Qué selección se convirtió en 2022 en la primera de África en llegar a una semifinal de un Mundial?",
    category: "Mundiales",
    difficulty: "media",
    option_a: "Ghana",
    option_b: "Marruecos",
    option_c: "Senegal",
    option_d: "Camerún",
    correct_answer: "b",
  },
  {
    question: "¿Qué jugador tiene el récord de más partidos disputados en la historia de los Mundiales?",
    category: "Individuales",
    difficulty: "dificil",
    option_a: "Lothar Matthäus",
    option_b: "Diego Maradona",
    option_c: "Lionel Messi",
    option_d: "Franz Beckenbauer",
    correct_answer: "c",
  },
  {
    question: "¿Qué selección ganó el Mundial de 1950 al vencer a Brasil como local, en el histórico 'Maracanazo'?",
    category: "Mundiales",
    difficulty: "dificil",
    option_a: "Argentina",
    option_b: "Uruguay",
    option_c: "Paraguay",
    option_d: "Chile",
    correct_answer: "b",
  },
  {
    question: "¿En qué edición del Mundial se utilizó por primera vez el VAR (videoarbitraje)?",
    category: "Reglas",
    difficulty: "media",
    option_a: "Brasil 2014",
    option_b: "Rusia 2018",
    option_c: "Catar 2022",
    option_d: "Sudáfrica 2010",
    correct_answer: "b",
  },
  {
    question: "¿Qué arquero ganó el primer Guante de Oro al mejor portero de un Mundial, en 1994?",
    category: "Individuales",
    difficulty: "dificil",
    option_a: "Michel Preud'homme",
    option_b: "Fabien Barthez",
    option_c: "Óscar Córdoba",
    option_d: "Jorge Campos",
    correct_answer: "a",
  },
  {
    question: "¿Cuál fue el resultado final del partido decisivo del Mundial 1950 entre Uruguay y Brasil?",
    category: "Mundiales",
    difficulty: "dificil",
    option_a: "Uruguay 2 - Brasil 1",
    option_b: "Uruguay 3 - Brasil 2",
    option_c: "Uruguay 1 - Brasil 0",
    option_d: "Uruguay 2 - Brasil 0",
    correct_answer: "a",
  },
  {
    question: "¿Qué jugador convirtió el gol más rápido en la historia de los Mundiales (10,8 segundos), en 2002?",
    category: "Mundiales",
    difficulty: "dificil",
    option_a: "Ronaldo Nazário",
    option_b: "Hakan Şükür",
    option_c: "Miroslav Klose",
    option_d: "Michael Owen",
    correct_answer: "b",
  },
  {
    question: "¿Qué selección ganó la primera Copa Rey Fahd en 1992, antecesora de la Copa Confederaciones?",
    category: "Historia",
    difficulty: "dificil",
    option_a: "Brasil",
    option_b: "Alemania",
    option_c: "Argentina",
    option_d: "México",
    correct_answer: "c",
  },
  {
    question: "¿Qué dos países coorganizaron el Mundial de 2002, el primero disputado en Asia?",
    category: "Mundiales",
    difficulty: "media",
    option_a: "China y Japón",
    option_b: "Japón y Corea del Sur",
    option_c: "Tailandia y Corea del Sur",
    option_d: "Corea del Sur y China",
    correct_answer: "b",
  },
  {
    question: "¿Cuántos goles convirtió Pelé en total a lo largo de los Mundiales que disputó?",
    category: "Individuales",
    difficulty: "dificil",
    option_a: "10",
    option_b: "12",
    option_c: "15",
    option_d: "9",
    correct_answer: "b",
  },
  {
    question: "¿Qué selección ganó el Mundial de 1974, disputado en Alemania?",
    category: "Mundiales",
    difficulty: "media",
    option_a: "Países Bajos",
    option_b: "Alemania Occidental",
    option_c: "Polonia",
    option_d: "Brasil",
    correct_answer: "b",
  },
  {
    question: "¿Qué jugador convirtió, en el mismo partido de cuartos de final del Mundial 1986, el gol de 'la Mano de Dios' y el 'Gol del Siglo'?",
    category: "Individuales",
    difficulty: "media",
    option_a: "Jorge Valdano",
    option_b: "Diego Maradona",
    option_c: "Jorge Burruchaga",
    option_d: "Claudio Caniggia",
    correct_answer: "b",
  },
  {
    question: "¿Qué selección ganó la Copa América 2021, venciendo a Brasil en el Maracaná?",
    category: "Copa América",
    difficulty: "media",
    option_a: "Uruguay",
    option_b: "Argentina",
    option_c: "Colombia",
    option_d: "Chile",
    correct_answer: "b",
  },
  {
    question: "¿Quién ganó el Balón de Oro 2018, cortando una década de dominio de Messi y Cristiano?",
    category: "Individuales",
    difficulty: "media",
    option_a: "Kylian Mbappé",
    option_b: "Antoine Griezmann",
    option_c: "Luka Modrić",
    option_d: "Virgil van Dijk",
    correct_answer: "c",
  },
  {
    question: "¿En qué estadio se disputó la final del Mundial 2014 entre Alemania y Argentina?",
    category: "Mundiales",
    difficulty: "media",
    option_a: "Arena Corinthians",
    option_b: "Mineirão",
    option_c: "Maracaná",
    option_d: "Arena Fonte Nova",
    correct_answer: "c",
  },
  {
    question: "¿Qué selección dio la sorpresa al ganar la Eurocopa 2004 siendo una de las menos favoritas?",
    category: "Eurocopa",
    difficulty: "media",
    option_a: "Portugal",
    option_b: "República Checa",
    option_c: "Grecia",
    option_d: "Dinamarca",
    correct_answer: "c",
  },
  {
    question: "¿Quién es el máximo goleador histórico de la selección argentina?",
    category: "Individuales",
    difficulty: "facil",
    option_a: "Gabriel Batistuta",
    option_b: "Lionel Messi",
    option_c: "Diego Maradona",
    option_d: "Sergio Agüero",
    correct_answer: "b",
  },
  {
    question: "¿Qué selección africana sorprendió al llegar a cuartos de final en el Mundial de 1990?",
    category: "Mundiales",
    difficulty: "dificil",
    option_a: "Nigeria",
    option_b: "Camerún",
    option_c: "Argelia",
    option_d: "Egipto",
    correct_answer: "b",
  },
  {
    question: "¿Quién convirtió el gol del título para España en la final del Mundial 2010?",
    category: "Mundiales",
    difficulty: "media",
    option_a: "David Villa",
    option_b: "Xavi Hernández",
    option_c: "Andrés Iniesta",
    option_d: "Fernando Torres",
    correct_answer: "c",
  },
  {
    question: "¿Cuántos Mundiales ganó Brasil, la selección más laureada del torneo?",
    category: "Mundiales",
    difficulty: "facil",
    option_a: "4",
    option_b: "5",
    option_c: "6",
    option_d: "3",
    correct_answer: "b",
  },
  {
    question: "¿En qué año se disputó el primer Mundial femenino oficial organizado por la FIFA?",
    category: "Mundiales",
    difficulty: "dificil",
    option_a: "1987",
    option_b: "1991",
    option_c: "1995",
    option_d: "1999",
    correct_answer: "b",
  },
  {
    question: "¿Qué selección ganó el Mundial femenino de 2023, el primero de su historia?",
    category: "Mundiales",
    difficulty: "media",
    option_a: "Inglaterra",
    option_b: "Estados Unidos",
    option_c: "España",
    option_d: "Suecia",
    correct_answer: "c",
  },
  {
    question: "¿Qué arquero fue campeón del mundo con Argentina en 2022 y ganó el Guante de Oro?",
    category: "Individuales",
    difficulty: "facil",
    option_a: "Franco Armani",
    option_b: "Emiliano Martínez",
    option_c: "Gerónimo Rulli",
    option_d: "Sergio Romero",
    correct_answer: "b",
  },
  {
    question: "¿Contra qué selección jugó Argentina la final del Mundial 2022?",
    category: "Mundiales",
    difficulty: "facil",
    option_a: "Croacia",
    option_b: "Marruecos",
    option_c: "Francia",
    option_d: "Brasil",
    correct_answer: "c",
  },
  {
    question: "¿Qué jugador convirtió el único triplete en la historia de una final de Mundial, en 1966?",
    category: "Mundiales",
    difficulty: "dificil",
    option_a: "Bobby Charlton",
    option_b: "Geoff Hurst",
    option_c: "Roger Hunt",
    option_d: "Martin Peters",
    correct_answer: "b",
  },
  {
    question: "¿Qué selección ganó la Eurocopa 2020, disputada en 2021 por la pandemia?",
    category: "Eurocopa",
    difficulty: "media",
    option_a: "Inglaterra",
    option_b: "Italia",
    option_c: "España",
    option_d: "Bélgica",
    correct_answer: "b",
  },
  {
    question: "¿Qué selección ganó la Copa América 2019, disputada en Brasil?",
    category: "Copa América",
    difficulty: "media",
    option_a: "Argentina",
    option_b: "Perú",
    option_c: "Brasil",
    option_d: "Chile",
    correct_answer: "c",
  },
  {
    question: "¿Qué país organizó el Mundial de 2010, el primero disputado en suelo africano?",
    category: "Mundiales",
    difficulty: "facil",
    option_a: "Nigeria",
    option_b: "Marruecos",
    option_c: "Sudáfrica",
    option_d: "Egipto",
    correct_answer: "c",
  },
  {
    question: "¿Qué selección es la única que participó en todos los Mundiales disputados hasta hoy?",
    category: "Mundiales",
    difficulty: "media",
    option_a: "Alemania",
    option_b: "Italia",
    option_c: "Brasil",
    option_d: "Argentina",
    correct_answer: "c",
  },
  {
    question: "¿Quién dirigió a la selección argentina campeona del Mundial 2022?",
    category: "Individuales",
    difficulty: "media",
    option_a: "Jorge Sampaoli",
    option_b: "Lionel Scaloni",
    option_c: "Diego Simeone",
    option_d: "Marcelo Gallardo",
    correct_answer: "b",
  },
  {
    question: "¿En qué Mundial debutó Pelé, consagrándose campeón con apenas 17 años?",
    category: "Mundiales",
    difficulty: "media",
    option_a: "1954",
    option_b: "1958",
    option_c: "1962",
    option_d: "1966",
    correct_answer: "b",
  },
  {
    question: "¿A qué selección venció Argentina en la final de la Copa América 2024?",
    category: "Copa América",
    difficulty: "media",
    option_a: "Uruguay",
    option_b: "Brasil",
    option_c: "Colombia",
    option_d: "Canadá",
    correct_answer: "c",
  },
];

// Slot 2: liga chilena, con foco en Universidad de Chile
const SLOT2_POOL = [
  {
    question: "¿En qué año se fundó Universidad de Chile, el club conocido como 'La U'?",
    category: "Liga Chilena",
    difficulty: "dificil",
    option_a: "1925",
    option_b: "1927",
    option_c: "1933",
    option_d: "1910",
    correct_answer: "b",
  },
  {
    question: "¿Qué título internacional ganó Universidad de Chile en 2011, el primero de su historia?",
    category: "Liga Chilena",
    difficulty: "dificil",
    option_a: "Copa Libertadores",
    option_b: "Recopa Sudamericana",
    option_c: "Copa Sudamericana",
    option_d: "Copa Merconorte",
    correct_answer: "c",
  },
  {
    question: "¿Qué entrenador argentino dirigió a Universidad de Chile durante su histórica campaña de 2011?",
    category: "Liga Chilena",
    difficulty: "dificil",
    option_a: "Marcelo Bielsa",
    option_b: "Jorge Sampaoli",
    option_c: "Gerardo Martino",
    option_d: "Marcelo Gallardo",
    correct_answer: "b",
  },
  {
    question: "¿Cómo se conoce al clásico entre Universidad de Chile y Universidad Católica?",
    category: "Liga Chilena",
    difficulty: "media",
    option_a: "Superclásico",
    option_b: "Clásico del Sur",
    option_c: "Clásico Universitario",
    option_d: "Clásico Capitalino",
    correct_answer: "c",
  },
  {
    question: "¿Cómo se conoce al clásico entre Colo-Colo y Universidad de Chile, el más popular del fútbol chileno?",
    category: "Liga Chilena",
    difficulty: "media",
    option_a: "Clásico Universitario",
    option_b: "Superclásico",
    option_c: "Clásico del Pacífico",
    option_d: "Gran Clásico",
    correct_answer: "b",
  },
  {
    question: "¿Con qué apodo se conoció al histórico equipo de Universidad de Chile campeón en la década de 1960?",
    category: "Liga Chilena",
    difficulty: "dificil",
    option_a: "El Ballet Azul",
    option_b: "La Máquina Azul",
    option_c: "Los Azules de Oro",
    option_d: "El Escuadrón Azul",
    correct_answer: "a",
  },
  {
    question: "¿Ante qué equipo argentino perdió Universidad de Chile la final de la Copa Libertadores de 1970?",
    category: "Liga Chilena",
    difficulty: "dificil",
    option_a: "Boca Juniors",
    option_b: "River Plate",
    option_c: "Estudiantes de La Plata",
    option_d: "Racing Club",
    correct_answer: "c",
  },
  {
    question: "¿En qué club chileno se formó y debutó profesionalmente Marcelo Salas antes de partir al fútbol internacional?",
    category: "Liga Chilena",
    difficulty: "media",
    option_a: "Colo-Colo",
    option_b: "Universidad de Chile",
    option_c: "Universidad Católica",
    option_d: "Cobreloa",
    correct_answer: "b",
  },
  {
    question: "¿Qué club chileno tiene más títulos de Primera División en la historia?",
    category: "Liga Chilena",
    difficulty: "media",
    option_a: "Universidad de Chile",
    option_b: "Universidad Católica",
    option_c: "Colo-Colo",
    option_d: "Cobreloa",
    correct_answer: "c",
  },
  {
    question: "¿Qué club chileno ganó la Copa Libertadores en 1991, siendo hasta hoy el único club de Chile en lograrlo?",
    category: "Liga Chilena",
    difficulty: "dificil",
    option_a: "Universidad de Chile",
    option_b: "Colo-Colo",
    option_c: "Universidad Católica",
    option_d: "Palestino",
    correct_answer: "b",
  },
  {
    question: "¿Qué jugador fundó el club Colo-Colo en 1925?",
    category: "Liga Chilena",
    difficulty: "dificil",
    option_a: "David Arellano",
    option_b: "Carlos Caszely",
    option_c: "Elías Figueroa",
    option_d: "Francisco Valdés",
    correct_answer: "a",
  },
  {
    question: "¿Qué club del norte de Chile llegó a dos finales consecutivas de la Copa Libertadores (1981 y 1982) sin poder consagrarse campeón?",
    category: "Liga Chilena",
    difficulty: "dificil",
    option_a: "Cobresal",
    option_b: "Deportes Antofagasta",
    option_c: "Cobreloa",
    option_d: "Deportes Iquique",
    correct_answer: "c",
  },
  {
    question: "¿En qué año Chile fue sede de la Copa del Mundo?",
    category: "Liga Chilena",
    difficulty: "media",
    option_a: "1958",
    option_b: "1962",
    option_c: "1966",
    option_d: "1970",
    correct_answer: "b",
  },
  {
    question: "¿Qué apodo recibe históricamente Universidad de Chile por sus destacadas giras internacionales?",
    category: "Liga Chilena",
    difficulty: "dificil",
    option_a: "El Romántico Viajero",
    option_b: "El Trotamundos Azul",
    option_c: "El Viajero Universitario",
    option_d: "El Nómade Azul",
    correct_answer: "a",
  },
  {
    question: "¿A qué selección venció Chile en la final de la Copa América 2015, disputada en su propio país, para ganar su primer título continental?",
    category: "Liga Chilena",
    difficulty: "media",
    option_a: "Brasil",
    option_b: "Uruguay",
    option_c: "Argentina",
    option_d: "Perú",
    correct_answer: "c",
  },
  {
    question: "¿Qué equipo enfrentó y venció Universidad de Chile en la final de la Copa Sudamericana 2011?",
    category: "Liga Chilena",
    difficulty: "dificil",
    option_a: "LDU Quito",
    option_b: "Independiente del Valle",
    option_c: "Emelec",
    option_d: "Barcelona SC",
    correct_answer: "a",
  },
  {
    question: "¿En qué estadio chileno se disputan tradicionalmente las grandes finales del fútbol nacional y los partidos de la selección?",
    category: "Liga Chilena",
    difficulty: "media",
    option_a: "Estadio Monumental",
    option_b: "Estadio Nacional",
    option_c: "Estadio Sausalito",
    option_d: "Estadio El Teniente",
    correct_answer: "b",
  },
  {
    question: "¿Cuántos títulos oficiales ganó Universidad de Chile durante su histórica temporada 2011 (Apertura, Copa Sudamericana y Clausura)?",
    category: "Liga Chilena",
    difficulty: "dificil",
    option_a: "2",
    option_b: "3",
    option_c: "4",
    option_d: "1",
    correct_answer: "b",
  },
  {
    question: "¿Quién fue el primer técnico de la selección chilena en ganar un título oficial en el fútbol profesional?",
    category: "Liga Chilena",
    difficulty: "media",
    option_a: "Marcelo Bielsa",
    option_b: "Jorge Sampaoli",
    option_c: "Gerardo Martino",
    option_d: "Ernesto Figueroa",
    correct_answer: "b",
  },
  {
    question: "¿Qué club chileno ha ganado más Copas Sudamericanas?",
    category: "Liga Chilena",
    difficulty: "dificil",
    option_a: "Universidad de Chile",
    option_b: "Colo-Colo",
    option_c: "Universidad Católica",
    option_d: "Palestino",
    correct_answer: "a",
  },
  {
    question: "¿Cómo se llama la principal barra de Universidad de Chile?",
    category: "Liga Chilena",
    difficulty: "media",
    option_a: "Los de Abajo",
    option_b: "La Garra Blanca",
    option_c: "Los Cruzados",
    option_d: "La Barra del Bulla",
    correct_answer: "a",
  },
  {
    question: "¿Quién es el máximo goleador histórico de la selección chilena?",
    category: "Liga Chilena",
    difficulty: "media",
    option_a: "Marcelo Salas",
    option_b: "Iván Zamorano",
    option_c: "Alexis Sánchez",
    option_d: "Eduardo Vargas",
    correct_answer: "c",
  },
  {
    question: "¿Cuántas Copas América ganó la selección chilena en su historia?",
    category: "Liga Chilena",
    difficulty: "facil",
    option_a: "1",
    option_b: "2",
    option_c: "3",
    option_d: "Ninguna",
    correct_answer: "b",
  },
  {
    question: "¿A qué selección venció Chile en la final de la Copa América Centenario 2016?",
    category: "Liga Chilena",
    difficulty: "media",
    option_a: "Colombia",
    option_b: "Argentina",
    option_c: "Brasil",
    option_d: "México",
    correct_answer: "b",
  },
  {
    question: "¿Qué arquero fue capitán de la selección chilena durante su generación dorada?",
    category: "Liga Chilena",
    difficulty: "media",
    option_a: "Claudio Bravo",
    option_b: "Johnny Herrera",
    option_c: "Sergio Vargas",
    option_d: "Miguel Pinto",
    correct_answer: "a",
  },
  {
    question: "¿Con qué apodo se conoce a los hinchas y al club Universidad Católica?",
    category: "Liga Chilena",
    difficulty: "facil",
    option_a: "Los Albos",
    option_b: "Los Cruzados",
    option_c: "Los Azules",
    option_d: "Los Piratas",
    correct_answer: "b",
  },
  {
    question: "¿En qué año fue fundado Colo-Colo?",
    category: "Liga Chilena",
    difficulty: "media",
    option_a: "1920",
    option_b: "1925",
    option_c: "1927",
    option_d: "1933",
    correct_answer: "b",
  },
  {
    question: "¿Qué entrenador argentino dirigió a Chile en el Mundial de Sudáfrica 2010?",
    category: "Liga Chilena",
    difficulty: "media",
    option_a: "Jorge Sampaoli",
    option_b: "Marcelo Bielsa",
    option_c: "Claudio Borghi",
    option_d: "Juan Antonio Pizzi",
    correct_answer: "b",
  },
  {
    question: "¿Qué jugador chileno ganó la Champions League con el Bayern Múnich en 2013?",
    category: "Liga Chilena",
    difficulty: "dificil",
    option_a: "Arturo Vidal",
    option_b: "Alexis Sánchez",
    option_c: "Gary Medel",
    option_d: "Charles Aránguiz",
    correct_answer: "a",
  },
  {
    question: "¿Qué puesto obtuvo Chile en el Mundial de 1962, su mejor actuación histórica?",
    category: "Liga Chilena",
    difficulty: "media",
    option_a: "Campeón",
    option_b: "Subcampeón",
    option_c: "Tercer lugar",
    option_d: "Cuarto lugar",
    correct_answer: "c",
  },
  {
    question: "¿Qué delantero fue figura de Universidad de Chile en 2011 y luego emigró al fútbol europeo?",
    category: "Liga Chilena",
    difficulty: "media",
    option_a: "Eduardo Vargas",
    option_b: "Ángelo Henríquez",
    option_c: "Junior Fernandes",
    option_d: "Gustavo Canales",
    correct_answer: "a",
  },
  {
    question: "¿Cómo se llama el estadio donde Universidad Católica hace de local?",
    category: "Liga Chilena",
    difficulty: "dificil",
    option_a: "Estadio Monumental",
    option_b: "San Carlos de Apoquindo",
    option_c: "Estadio Santa Laura",
    option_d: "Estadio El Teniente",
    correct_answer: "b",
  },
  {
    question: "¿Qué selección eliminó a Chile por penales en los octavos del Mundial 2014?",
    category: "Liga Chilena",
    difficulty: "media",
    option_a: "Países Bajos",
    option_b: "Brasil",
    option_c: "Colombia",
    option_d: "España",
    correct_answer: "b",
  },
  {
    question: "¿Qué jugador chileno vistió las camisetas de Barcelona, Arsenal y Manchester United?",
    category: "Liga Chilena",
    difficulty: "media",
    option_a: "Arturo Vidal",
    option_b: "Alexis Sánchez",
    option_c: "Claudio Bravo",
    option_d: "Mauricio Isla",
    correct_answer: "b",
  },
  {
    question: "¿Con qué apodo se conoce popularmente a Colo-Colo?",
    category: "Liga Chilena",
    difficulty: "facil",
    option_a: "El Cacique",
    option_b: "El Bulla",
    option_c: "El Pirata",
    option_d: "El León",
    correct_answer: "a",
  },
  {
    question: "¿Cómo se llama el estadio donde Colo-Colo hace de local?",
    category: "Liga Chilena",
    difficulty: "media",
    option_a: "Estadio Nacional",
    option_b: "Estadio Monumental David Arellano",
    option_c: "Estadio Santa Laura",
    option_d: "San Carlos de Apoquindo",
    correct_answer: "b",
  },
  {
    question: "¿Qué mediocampista chileno es conocido como 'El Rey Arturo'?",
    category: "Liga Chilena",
    difficulty: "facil",
    option_a: "Charles Aránguiz",
    option_b: "Arturo Vidal",
    option_c: "Gary Medel",
    option_d: "Marcelo Díaz",
    correct_answer: "b",
  },
  {
    question: "¿En qué clubes europeos de élite atajó el chileno Claudio Bravo?",
    category: "Liga Chilena",
    difficulty: "dificil",
    option_a: "Barcelona y Manchester City",
    option_b: "Real Madrid y Chelsea",
    option_c: "Atlético de Madrid y Juventus",
    option_d: "Sevilla y Bayern Múnich",
    correct_answer: "a",
  },
  {
    question: "¿Qué defensor chileno fue apodado 'El Pitbull' por su carácter en la cancha?",
    category: "Liga Chilena",
    difficulty: "media",
    option_a: "Gonzalo Jara",
    option_b: "Gary Medel",
    option_c: "Mauricio Isla",
    option_d: "Jean Beausejour",
    correct_answer: "b",
  },
  {
    question: "¿En qué año Universidad de Chile ganó su primer título de Primera División?",
    category: "Liga Chilena",
    difficulty: "dificil",
    option_a: "1940",
    option_b: "1959",
    option_c: "1962",
    option_d: "1969",
    correct_answer: "a",
  },
];

// Slot 3: fútbol europeo, MUCHO más difícil (Champions, detalles muy específicos)
const SLOT3_POOL = [
  {
    question: "¿Quién ganó la Champions League 2007?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "Liverpool",
    option_b: "Chelsea",
    option_c: "AC Milan",
    option_d: "Bayern Múnich",
    correct_answer: "c",
  },
  {
    question: "¿Qué equipo ganó la Champions League 2006?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "AC Milan",
    option_b: "Barcelona",
    option_c: "Arsenal",
    option_d: "Liverpool",
    correct_answer: "a",
  },
  {
    question: "¿Quién ganó la Champions League 2005?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "Bayern Múnich",
    option_b: "Liverpool",
    option_c: "Chelsea",
    option_d: "Valencia",
    correct_answer: "b",
  },
  {
    question: "¿Qué equipo ganó la Champions League 2008?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "Manchester United",
    option_b: "Real Madrid",
    option_c: "Barcelona",
    option_d: "Chelsea",
    correct_answer: "a",
  },
  {
    question: "¿Quién fue goleador de la Champions League 2007-08 con 12 goles?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "Cristiano Ronaldo",
    option_b: "Lionel Messi",
    option_c: "Eidur Gudjohnsen",
    option_d: "Didier Drogba",
    correct_answer: "a",
  },
  {
    question: "¿Qué club ganó las primeras 5 Copas de Europa consecutivas, entre 1956 y 1960?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "Barcelona",
    option_b: "Real Madrid",
    option_c: "Benfica",
    option_d: "AC Milan",
    correct_answer: "b",
  },
  {
    question: "¿En qué año se disputó la mayor remontada de Champions: Barcelona 6-1 PSG?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "2015",
    option_b: "2016",
    option_c: "2017",
    option_d: "2014",
    correct_answer: "b",
  },
  {
    question: "¿Quién fue máximo goleador histórico de Champions hasta 2017?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "Lionel Messi",
    option_b: "Cristiano Ronaldo",
    option_c: "Raúl González",
    option_d: "Alfredo Di Stéfano",
    correct_answer: "b",
  },
  {
    question: "¿Qué equipo fue el primer tricampeón de Champions consecutivas en la era moderna?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "Bayern Múnich",
    option_b: "AC Milan",
    option_c: "Real Madrid",
    option_d: "Liverpool",
    correct_answer: "a",
  },
  {
    question: "¿Quién ganó la Champions League 2000?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "Real Madrid",
    option_b: "Bayern Múnich",
    option_c: "Valencia",
    option_d: "Juventus",
    correct_answer: "a",
  },
  {
    question: "¿En qué ciudad se disputó la final de Champions 1999 donde Manchester United remontó en los últimos minutos?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "Estambul",
    option_b: "Barcelona",
    option_c: "Róterdam",
    option_d: "Estocolmo",
    correct_answer: "a",
  },
  {
    question: "¿Qué equipo ganó la Copa de Europa 1980 ganando desde fuera del campo?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "Liverpool",
    option_b: "Nottingham Forest",
    option_c: "Aston Villa",
    option_d: "Bayern Múnich",
    correct_answer: "a",
  },
  {
    question: "¿Cuántos títulos de Champions tiene Real Madrid hasta 2024?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "13",
    option_b: "14",
    option_c: "15",
    option_d: "12",
    correct_answer: "c",
  },
  {
    question: "¿Quién ganó la Champions League 2001?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "AC Milan",
    option_b: "Bayern Múnich",
    option_c: "Juventus",
    option_d: "Valencia",
    correct_answer: "a",
  },
  {
    question: "¿Qué equipo fue el primero en ganar la Champions League con entrenador español desde el siglo XX?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "Barcelona",
    option_b: "Real Madrid",
    option_c: "Villarreal",
    option_d: "Atlético Madrid",
    correct_answer: "a",
  },
  {
    question: "¿En qué año Barcelona ganó su primer Champions League?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "1990",
    option_b: "1992",
    option_c: "1994",
    option_d: "1996",
    correct_answer: "b",
  },
  {
    question: "¿Quién ganó la Champions League 2002?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "Bayern Múnich",
    option_b: "Real Madrid",
    option_c: "Valencia",
    option_d: "Juventus",
    correct_answer: "b",
  },
  {
    question: "¿Qué equipo inglés ganó la Champions League 2019?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "Manchester City",
    option_b: "Liverpool",
    option_c: "Manchester United",
    option_d: "Chelsea",
    correct_answer: "b",
  },
  {
    question: "¿Cuántos balones de oro ganó Messi jugando en Europa?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "6",
    option_b: "7",
    option_c: "8",
    option_d: "5",
    correct_answer: "c",
  },
  {
    question: "¿Qué equipo ganó la Champions League 2003?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "AC Milan",
    option_b: "Juventus",
    option_c: "Valencia",
    option_d: "Real Madrid",
    correct_answer: "a",
  },
  {
    question: "¿Qué club ganó la Champions League 2004, dirigido por José Mourinho?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "Mónaco",
    option_b: "Porto",
    option_c: "Deportivo La Coruña",
    option_d: "Chelsea",
    correct_answer: "b",
  },
  {
    question: "¿Qué club ganó la Champions 2012 en penales ante el Bayern, en el propio estadio del Bayern?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "Chelsea",
    option_b: "Real Madrid",
    option_c: "Barcelona",
    option_d: "Manchester City",
    correct_answer: "a",
  },
  {
    question: "¿Qué club ganó la Champions 2013 en la final íntegramente alemana ante el Borussia Dortmund?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "Bayer Leverkusen",
    option_b: "Schalke 04",
    option_c: "Bayern Múnich",
    option_d: "RB Leipzig",
    correct_answer: "c",
  },
  {
    question: "¿Qué club ganó la Champions 2010 dirigido por José Mourinho, completando un triplete?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "AC Milan",
    option_b: "Inter de Milán",
    option_c: "Juventus",
    option_d: "Roma",
    correct_answer: "b",
  },
  {
    question: "¿Qué club venció al Manchester City en la final de la Champions League 2021?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "Liverpool",
    option_b: "Chelsea",
    option_c: "Real Madrid",
    option_d: "PSG",
    correct_answer: "b",
  },
  {
    question: "¿Qué club completó en 2023 el triplete de Liga, Copa y Champions League?",
    category: "Europa",
    difficulty: "media",
    option_a: "Manchester City",
    option_b: "Inter de Milán",
    option_c: "Real Madrid",
    option_d: "Bayern Múnich",
    correct_answer: "a",
  },
  {
    question: "¿Qué club holandés ganó la Champions League en 1995 con un plantel plagado de juveniles?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "PSV Eindhoven",
    option_b: "Feyenoord",
    option_c: "Ajax",
    option_d: "AZ Alkmaar",
    correct_answer: "c",
  },
  {
    question: "¿Qué club alemán ganó la Champions League 1997 venciendo a la Juventus en la final?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "Bayern Múnich",
    option_b: "Borussia Dortmund",
    option_c: "Werder Bremen",
    option_d: "Hamburgo",
    correct_answer: "b",
  },
  {
    question: "¿Qué club español ganó la Europa League 2021, su primer título europeo?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "Sevilla",
    option_b: "Real Sociedad",
    option_c: "Villarreal",
    option_d: "Athletic Club",
    correct_answer: "c",
  },
  {
    question: "¿Quién tiene el récord de más goles en una sola edición de la Champions League, con 17?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "Lionel Messi",
    option_b: "Cristiano Ronaldo",
    option_c: "Robert Lewandowski",
    option_d: "Karim Benzema",
    correct_answer: "b",
  },
  {
    question: "¿Qué club ganó la Champions 2016 tras vencer al Atlético de Madrid en penales?",
    category: "Europa",
    difficulty: "media",
    option_a: "Barcelona",
    option_b: "Real Madrid",
    option_c: "Bayern Múnich",
    option_d: "Juventus",
    correct_answer: "b",
  },
  {
    question: "¿En qué año el Barcelona logró su primer triplete de Liga, Copa y Champions?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "2006",
    option_b: "2009",
    option_c: "2011",
    option_d: "2015",
    correct_answer: "b",
  },
  {
    question: "¿Qué club italiano es apodado 'La Vecchia Signora' (La Vieja Dama)?",
    category: "Europa",
    difficulty: "media",
    option_a: "AC Milan",
    option_b: "Inter de Milán",
    option_c: "Juventus",
    option_d: "Roma",
    correct_answer: "c",
  },
  {
    question: "¿Qué club tiene la mayor cantidad de títulos de la Bundesliga alemana?",
    category: "Europa",
    difficulty: "facil",
    option_a: "Borussia Dortmund",
    option_b: "Bayern Múnich",
    option_c: "Hamburgo",
    option_d: "Werder Bremen",
    correct_answer: "b",
  },
  {
    question: "¿En qué final el Real Madrid conquistó 'La Décima' con gol de Sergio Ramos en el minuto 93?",
    category: "Europa",
    difficulty: "dificil",
    option_a: "2012",
    option_b: "2014",
    option_c: "2016",
    option_d: "2018",
    correct_answer: "b",
  },
  {
    question: "¿Qué club ganó la Champions League 2015 completando un triplete?",
    category: "Europa",
    difficulty: "media",
    option_a: "Barcelona",
    option_b: "Juventus",
    option_c: "Bayern Múnich",
    option_d: "Real Madrid",
    correct_answer: "a",
  },
  {
    question: "¿Qué club ganó la Champions League 2020, venciendo al PSG en la final?",
    category: "Europa",
    difficulty: "media",
    option_a: "Liverpool",
    option_b: "Bayern Múnich",
    option_c: "RB Leipzig",
    option_d: "Manchester City",
    correct_answer: "b",
  },
  {
    question: "¿Qué club ganó la Champions League 2022 tras vencer al Liverpool en la final de París?",
    category: "Europa",
    difficulty: "media",
    option_a: "Manchester City",
    option_b: "Real Madrid",
    option_c: "Villarreal",
    option_d: "Chelsea",
    correct_answer: "b",
  },
  {
    question: "¿Qué entrenador ganó la Champions League con dos clubes distintos: Porto e Inter de Milán?",
    category: "Europa",
    difficulty: "media",
    option_a: "Carlo Ancelotti",
    option_b: "Pep Guardiola",
    option_c: "José Mourinho",
    option_d: "Rafa Benítez",
    correct_answer: "c",
  },
  {
    question: "¿Qué club tiene la mayor cantidad de títulos de la Serie A italiana?",
    category: "Europa",
    difficulty: "media",
    option_a: "AC Milan",
    option_b: "Inter de Milán",
    option_c: "Juventus",
    option_d: "Roma",
    correct_answer: "c",
  },
];

// Modo B: Pool de "¿Quién es más...?"
const QUIEN_ES_MAS_POOL = [
  "¿Quién es más probable que haga el ridículo en una final?",
  "¿Quién es más probable que discuta con el árbitro a través de la tele?",
  "¿Quién es más probable que se despierte a las 4am para ver un partido?",
  "¿Quién es más probable que apueste su sueldo entero a un partido?",
  "¿Quién es más probable que tenga la camiseta más cara del grupo?",
  "¿Quién es más probable que se cambie de hincha por conveniencia?",
  "¿Quién es más probable que se acuerde de un resultado de hace 20 años?",
  "¿Quién es más probable que llore si su equipo pierde una final?",
  "¿Quién es más probable que llegue tarde a ver un partido?",
  "¿Quién es más probable que discuta de fútbol hasta las 3 de la mañana?",
  "¿Quién es más probable que se pierda el gol importante por estar en el baño?",
  "¿Quién es más probable que hable de fútbol hasta en un casamiento?",
  "¿Quién es más probable que se olvide de responder el trivia de hoy?",
  "¿Quién es más probable que festeje un gol solo en su casa como si estuviera en la cancha?",
  "¿Quién es más probable que diga 'yo lo hubiera atajado'?",
  "¿Quién es más probable que compre una camiseta y nunca se la ponga?",
  "¿Quién es más probable que se pelee por un gol en el picadito del domingo?",
  "¿Quién es más probable que se sepa la alineación completa de memoria?",
  "¿Quién es más probable que falle la pregunta de hoy?",
  "¿Quién es más probable que llame llorando después de una derrota?",
  "¿Quién es más probable que se compre la camiseta nueva el día que sale?",
  "¿Quién es más probable que insulte a la tele estando solo?",
  "¿Quién es más probable que se pelee con un hincha rival por WhatsApp?",
  "¿Quién es más probable que invente una estadística para ganar una discusión?",
  "¿Quién es más probable que se haga hincha de un equipo europeo por la camiseta?",
  "¿Quién es más probable que llegue al asado hablando de fútbol y se vaya hablando de fútbol?",
  "¿Quién es más probable que le ponga el nombre de un jugador a su mascota?",
  "¿Quién es más probable que mire un partido de una liga que no conoce?",
  "¿Quién es más probable que se sepa el sueldo de todos los jugadores?",
  "¿Quién es más probable que cante el himno del club en la ducha?",
  "¿Quién es más probable que abandone el grupo si pierde una apuesta?",
  "¿Quién es más probable que jure que 'ya lo había dicho' después de cada resultado?",
  "¿Quién es más probable que se ponga la camiseta para ver el partido por tele?",
  "¿Quién es más probable que discuta con el VAR desde el sillón?",
  "¿Quién es más probable que se quede dormido en el entretiempo?",
  "¿Quién es más probable que arme una tabla de posiciones en Excel?",
  "¿Quién es más probable que le eche la culpa al árbitro siempre?",
  "¿Quién es más probable que no perdone nunca un gol en contra?",
  "¿Quién es más probable que se emocione con un video de goles viejos?",
  "¿Quién es más probable que organice el próximo picadito del grupo?",
];

// Modo B: Pool de "¿Qué prefieres...?" (prompt fijo + 2 opciones concretas)
const QUE_PREFIERES_POOL = [
  { option_a: "Perder 5-0 en casa", option_b: "Perder 1-0 de visitante" },
  { option_a: "Un goleador inconsistente", option_b: "Un portero que falla a veces" },
  { option_a: "Un partido aburrido 1-0", option_b: "Un partido caótico 4-4" },
  { option_a: "Que se suspenda tu partido", option_b: "Que lo gane el rival" },
  { option_a: "Perder una final", option_b: "Perder al mejor jugador antes del torneo" },
  { option_a: "Un arbitraje que te beneficie", option_b: "Un arbitraje justo" },
  { option_a: "Un equipo joven y prometedor", option_b: "Un equipo veterano ganador" },
  { option_a: "El ataque espectacular", option_b: "La defensa de acero" },
  { option_a: "Una goleada en contra", option_b: "Perder 1-0 en el último minuto" },
  { option_a: "Ver a tu equipo perder", option_b: "No poder verlo jugar" },
  { option_a: "Ser campeón aburrido", option_b: "Ser subcampeón emocionante" },
  { option_a: "Un técnico exigente", option_b: "Un técnico permisivo" },
  { option_a: "Muchos partidos aburridos", option_b: "Pocos partidos espectaculares" },
  { option_a: "Un equipo local malo", option_b: "Un equipo extranjero ganador" },
  { option_a: "Un gol de suerte propio", option_b: "Un gol hermoso del rival" },
  { option_a: "Ganar de forma fea", option_b: "Perder de forma hermosa" },
  { option_a: "Un fichaje estrella", option_b: "Un equipo equilibrado" },
  { option_a: "Jugar siempre", option_b: "Entrenar bajo presión" },
  { option_a: "Un rival clásico", option_b: "Un rival impredecible" },
  { option_a: "Un empate controvertido", option_b: "Una derrota justa" },
  { option_a: "Ganar el clásico y salir último", option_b: "Salir campeón perdiendo los dos clásicos" },
  { option_a: "Ver todos los partidos solo", option_b: "Verlos todos con hinchas del rival" },
  { option_a: "Que tu equipo ascienda", option_b: "Que el rival descienda" },
  { option_a: "Un ídolo que se queda toda su carrera", option_b: "Un crack que se va en un año" },
  { option_a: "Jugar la final de local", option_b: "Jugarla en cancha neutral" },
  { option_a: "Que te cobren un penal inventado a favor", option_b: "Ganar sin ayuda del árbitro" },
  { option_a: "Un DT que gana feo", option_b: "Un DT que juega lindo y pierde" },
  { option_a: "Ir a la cancha siempre", option_b: "Verlo todo en HD desde el sillón" },
  { option_a: "Un plantel de juveniles del club", option_b: "Un plantel lleno de refuerzos caros" },
  { option_a: "Que tu equipo gane la copa", option_b: "Que el rival no gane nada en 10 años" },
  { option_a: "Ganar por penales", option_b: "Perder jugando mejor" },
  { option_a: "Un arquero que ataja penales", option_b: "Un delantero que los patea todos" },
  { option_a: "Saber el resultado antes del partido", option_b: "No poder ver ningún partido en un mes" },
  { option_a: "Un equipo que nunca baja", option_b: "Un equipo que sube y baja pero pelea títulos" },
  { option_a: "Que se juegue siempre de día", option_b: "Que se juegue siempre de noche" },
  { option_a: "Un clásico sin hinchada visitante", option_b: "Un clásico en cancha vacía" },
  { option_a: "Que tu jugador favorito se retire en el club", option_b: "Que gane un Mundial en otro lado" },
  { option_a: "Ganar el torneo local", option_b: "Ganar la copa internacional" },
  { option_a: "Que tu equipo juegue con 10 toda la final y gane", option_b: "Ganar cómodo y aburrido" },
  { option_a: "Una remontada épica", option_b: "Una victoria tranquila 3-0" },
].map((o) => ({ prompt: "¿Qué prefieres?", option_a: o.option_a, option_b: o.option_b }));

const NUM_DAYS = 40;

// El seed corre en cada arranque del server, así que un deploy a mitad del día
// vuelve a pasar por las preguntas de hoy. Si alguien ya respondió una, se deja
// como está: cambiarle el texto por debajo dejaría las respuestas guardadas
// apuntando a una pregunta que nadie llegó a ver.
async function hasAnswers(table, column, questionId) {
  const result = await db.execute({
    sql: `SELECT 1 FROM ${table} WHERE ${column} = ? LIMIT 1`,
    args: [questionId],
  });
  return result.rows.length > 0;
}

async function upsertQuestion(q, scheduled_date, slot) {
  const existing = await db.execute({
    sql: "SELECT id FROM questions WHERE scheduled_date = ? AND slot = ?",
    args: [scheduled_date, slot],
  });
  if (existing.rows.length > 0 && (await hasAnswers("answers", "question_id", existing.rows[0].id))) {
    return;
  }

  const updateResult = await db.execute({
    sql: `UPDATE questions SET
            question = ?, category = ?, difficulty = ?,
            option_a = ?, option_b = ?, option_c = ?, option_d = ?, correct_answer = ?
          WHERE scheduled_date = ? AND slot = ?`,
    args: [
      q.question,
      q.category,
      q.difficulty,
      q.option_a,
      q.option_b,
      q.option_c,
      q.option_d,
      q.correct_answer,
      scheduled_date,
      slot,
    ],
  });

  if (updateResult.rowsAffected === 0) {
    await db.execute({
      sql: `INSERT INTO questions
        (question, category, difficulty, option_a, option_b, option_c, option_d, correct_answer, scheduled_date, slot)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      args: [
        q.question,
        q.category,
        q.difficulty,
        q.option_a,
        q.option_b,
        q.option_c,
        q.option_d,
        q.correct_answer,
        scheduled_date,
        slot,
      ],
    });
  }
}

async function upsertSpecialQuestion(type, prompt, scheduled_date, option_a = null, option_b = null) {
  const existing = await db.execute({
    sql: "SELECT id FROM special_questions WHERE type = ? AND scheduled_date = ?",
    args: [type, scheduled_date],
  });
  if (
    existing.rows.length > 0 &&
    (await hasAnswers("special_answers", "special_question_id", existing.rows[0].id))
  ) {
    return;
  }

  const updateResult = await db.execute({
    sql: "UPDATE special_questions SET prompt = ?, option_a = ?, option_b = ? WHERE type = ? AND scheduled_date = ?",
    args: [prompt, option_a, option_b, type, scheduled_date],
  });

  if (updateResult.rowsAffected === 0) {
    await db.execute({
      sql: "INSERT INTO special_questions (type, prompt, option_a, option_b, scheduled_date) VALUES (?, ?, ?, ?, ?)",
      args: [type, prompt, option_a, option_b, scheduled_date],
    });
  }
}

async function seed() {
  await initSchema();

  for (let day = 0; day < NUM_DAYS; day++) {
    const scheduled_date = dateOffset(day);

    // Modo A: trivia normal
    await upsertQuestion(SLOT1_POOL[day % SLOT1_POOL.length], scheduled_date, 1);
    await upsertQuestion(SLOT2_POOL[day % SLOT2_POOL.length], scheduled_date, 2);
    await upsertQuestion(SLOT3_POOL[day % SLOT3_POOL.length], scheduled_date, 3);

    // Modo B: preguntas especiales (comunes a todos los grupos)
    await upsertSpecialQuestion("quien_es_mas", QUIEN_ES_MAS_POOL[day % QUIEN_ES_MAS_POOL.length], scheduled_date);
    const qp = QUE_PREFIERES_POOL[day % QUE_PREFIERES_POOL.length];
    await upsertSpecialQuestion("que_prefieres", qp.prompt, scheduled_date, qp.option_a, qp.option_b);
  }

  // Versiones anteriores del seed pre-creaban las preguntas de personalidad
  // para los 20 días siguientes, lo que congelaba al protagonista con la lista
  // de miembros de ese momento. Ahora las arma /api/mode-b el mismo día, así
  // que las futuras que quedaron dando vueltas se borran para que se
  // regeneren con la rotación nueva. Sólo las de fechas futuras: por
  // definición nadie pudo responderlas todavía.
  const cleanup = await db.execute({
    sql: "DELETE FROM personality_questions WHERE scheduled_date > ?",
    args: [dateOffset(0)],
  });
  if (cleanup.rowsAffected > 0) {
    console.log(`Limpiadas ${cleanup.rowsAffected} preguntas de personalidad futuras pre-creadas.`);
  }

  console.log(
    `Seed completado: ${NUM_DAYS} días x 3 preguntas trivia (Modo A) + 2 preguntas especiales (Modo B).`
  );
  console.log(`Modo A: General / Liga Chilena / Europa (Aumentada dificultad)`);
  console.log(`Modo B: ¿Quién es más? / ¿Qué prefieres? (la de personalidad la arma /api/mode-b por grupo)`);
  process.exit(0);
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
