import "dotenv/config";
import { db, initSchema } from "./client.js";

function dateOffset(days) {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}

const QUESTIONS = [
  {
    question: "¿Quién es el máximo goleador histórico en la historia de los Mundiales de fútbol?",
    category: "Individuales",
    difficulty: "dificil",
    option_a: "Ronaldo Nazário",
    option_b: "Just Fontaine",
    option_c: "Miroslav Klose",
    option_d: "Gerd Müller",
    correct_answer: "c",
  },
  {
    question: "¿Qué selección ganó el primer Mundial de fútbol de la historia, disputado en 1930?",
    category: "Mundiales",
    difficulty: "media",
    option_a: "Argentina",
    option_b: "Uruguay",
    option_c: "Brasil",
    option_d: "Italia",
    correct_answer: "b",
  },
  {
    question: "¿Qué arquero es el único portero en la historia en ganar el Balón de Oro, en 1963?",
    category: "Individuales",
    difficulty: "dificil",
    option_a: "Gordon Banks",
    option_b: "Dino Zoff",
    option_c: "Gianluigi Buffon",
    option_d: "Lev Yashin",
    correct_answer: "d",
  },
  {
    question: "¿Qué club ganó la primera edición de la Copa Libertadores, en 1960?",
    category: "Libertadores",
    difficulty: "dificil",
    option_a: "River Plate",
    option_b: "Nacional",
    option_c: "Peñarol",
    option_d: "Olimpia",
    correct_answer: "c",
  },
  {
    question: "¿Quién tiene el récord de más goles en una sola edición de un Mundial, con 13 goles en 1958?",
    category: "Mundiales",
    difficulty: "dificil",
    option_a: "Pelé",
    option_b: "Just Fontaine",
    option_c: "Sándor Kocsis",
    option_d: "Eusébio",
    correct_answer: "b",
  },
  {
    question: "¿Qué selección ganó la primera edición de la Eurocopa, en 1960?",
    category: "Eurocopa",
    difficulty: "dificil",
    option_a: "Unión Soviética",
    option_b: "Yugoslavia",
    option_c: "Checoslovaquia",
    option_d: "Francia",
    correct_answer: "a",
  },
  {
    question: "¿En qué país se disputó el Mundial de 1970, donde Brasil ganó su tercer título?",
    category: "Mundiales",
    difficulty: "media",
    option_a: "Chile",
    option_b: "Argentina",
    option_c: "México",
    option_d: "Alemania",
    correct_answer: "c",
  },
  {
    question: "¿Quién fue el máximo goleador del Mundial de Brasil 2014, con 6 goles?",
    category: "Mundiales",
    difficulty: "dificil",
    option_a: "Lionel Messi",
    option_b: "Thomas Müller",
    option_c: "Neymar",
    option_d: "James Rodríguez",
    correct_answer: "d",
  },
  {
    question: "¿Qué selección se convirtió en 2022 en la primera de África en llegar a una semifinal de un Mundial?",
    category: "Mundiales",
    difficulty: "media",
    option_a: "Ghana",
    option_b: "Marruecos",
    option_c: "Senegal",
    option_d: "Camerún",
    correct_answer: "b",
  },
  {
    question: "¿Qué jugador tiene el récord de más partidos disputados en la historia de los Mundiales?",
    category: "Individuales",
    difficulty: "dificil",
    option_a: "Lothar Matthäus",
    option_b: "Diego Maradona",
    option_c: "Lionel Messi",
    option_d: "Franz Beckenbauer",
    correct_answer: "c",
  },
  {
    question: "¿Qué selección ganó el Mundial de 1950 al vencer a Brasil como local, en el histórico 'Maracanazo'?",
    category: "Mundiales",
    difficulty: "dificil",
    option_a: "Argentina",
    option_b: "Uruguay",
    option_c: "Paraguay",
    option_d: "Chile",
    correct_answer: "b",
  },
  {
    question: "¿En qué edición del Mundial se utilizó por primera vez el VAR (videoarbitraje)?",
    category: "Reglas",
    difficulty: "media",
    option_a: "Brasil 2014",
    option_b: "Rusia 2018",
    option_c: "Catar 2022",
    option_d: "Sudáfrica 2010",
    correct_answer: "b",
  },
  {
    question: "¿Qué arquero ganó el primer Guante de Oro al mejor portero de un Mundial, en 1994?",
    category: "Individuales",
    difficulty: "dificil",
    option_a: "Michel Preud'homme",
    option_b: "Fabien Barthez",
    option_c: "Óscar Córdoba",
    option_d: "Jorge Campos",
    correct_answer: "a",
  },
  {
    question: "¿Cuál fue el resultado final del partido decisivo del Mundial 1950 entre Uruguay y Brasil?",
    category: "Mundiales",
    difficulty: "dificil",
    option_a: "Uruguay 2 - Brasil 1",
    option_b: "Uruguay 3 - Brasil 2",
    option_c: "Uruguay 1 - Brasil 0",
    option_d: "Uruguay 2 - Brasil 0",
    correct_answer: "a",
  },
  {
    question: "¿Qué jugador convirtió el gol más rápido en la historia de los Mundiales (10,8 segundos), en 2002?",
    category: "Mundiales",
    difficulty: "dificil",
    option_a: "Ronaldo Nazário",
    option_b: "Hakan Şükür",
    option_c: "Miroslav Klose",
    option_d: "Michael Owen",
    correct_answer: "b",
  },
  {
    question: "¿Qué selección ganó la primera Copa Rey Fahd en 1992, antecesora de la Copa Confederaciones?",
    category: "Historia",
    difficulty: "dificil",
    option_a: "Brasil",
    option_b: "Alemania",
    option_c: "Argentina",
    option_d: "México",
    correct_answer: "c",
  },
  {
    question: "¿Qué dos países coorganizaron el Mundial de 2002, el primero disputado en Asia?",
    category: "Mundiales",
    difficulty: "media",
    option_a: "China y Japón",
    option_b: "Japón y Corea del Sur",
    option_c: "Tailandia y Corea del Sur",
    option_d: "Corea del Sur y China",
    correct_answer: "b",
  },
  {
    question: "¿Cuántos goles convirtió Pelé en total a lo largo de los Mundiales que disputó?",
    category: "Individuales",
    difficulty: "dificil",
    option_a: "10",
    option_b: "12",
    option_c: "15",
    option_d: "9",
    correct_answer: "b",
  },
  {
    question: "¿Qué selección ganó el Mundial de 1974, disputado en Alemania?",
    category: "Mundiales",
    difficulty: "media",
    option_a: "Países Bajos",
    option_b: "Alemania Occidental",
    option_c: "Polonia",
    option_d: "Brasil",
    correct_answer: "b",
  },
  {
    question:
      "¿Qué jugador convirtió, en el mismo partido de cuartos de final del Mundial 1986, el gol de 'la Mano de Dios' y el 'Gol del Siglo'?",
    category: "Individuales",
    difficulty: "media",
    option_a: "Jorge Valdano",
    option_b: "Diego Maradona",
    option_c: "Jorge Burruchaga",
    option_d: "Claudio Caniggia",
    correct_answer: "b",
  },
  {
    question: "¿Qué club ganó la primera edición de la Copa de Europa / Champions League, en 1955-56?",
    category: "Champions League",
    difficulty: "dificil",
    option_a: "AC Milan",
    option_b: "Real Madrid",
    option_c: "Benfica",
    option_d: "Manchester United",
    correct_answer: "b",
  },
  {
    question: "¿Cuál es el máximo goleador histórico de la Champions League?",
    category: "Champions League",
    difficulty: "media",
    option_a: "Karim Benzema",
    option_b: "Robert Lewandowski",
    option_c: "Cristiano Ronaldo",
    option_d: "Lionel Messi",
    correct_answer: "c",
  },
  {
    question: "¿Qué club ganó cinco Copas de Europa consecutivas entre 1956 y 1960?",
    category: "Champions League",
    difficulty: "dificil",
    option_a: "Benfica",
    option_b: "Real Madrid",
    option_c: "Inter de Milán",
    option_d: "AC Milan",
    correct_answer: "b",
  },
  {
    question:
      "¿Qué club inglés ganó la Copa de Europa en 1979 y 1980 de forma consecutiva, dirigido por Brian Clough?",
    category: "Champions League",
    difficulty: "dificil",
    option_a: "Liverpool",
    option_b: "Aston Villa",
    option_c: "Nottingham Forest",
    option_d: "Leeds United",
    correct_answer: "c",
  },
  {
    question:
      "¿Qué club rumano se consagró campeón de la Copa de Europa en 1986, venciendo al Barcelona en los penales?",
    category: "Champions League",
    difficulty: "dificil",
    option_a: "Dinamo de Bucarest",
    option_b: "Steaua de Bucarest",
    option_c: "Rapid de Bucarest",
    option_d: "CFR Cluj",
    correct_answer: "b",
  },
  {
    question:
      "¿Qué club escocés, conocido como los 'Lisbon Lions', fue el primer equipo británico en ganar la Copa de Europa, en 1967?",
    category: "Champions League",
    difficulty: "dificil",
    option_a: "Rangers",
    option_b: "Celtic",
    option_c: "Aberdeen",
    option_d: "Hibernian",
    correct_answer: "b",
  },
  {
    question: "¿Qué club ganó su primera Champions League en 1997, venciendo a la Juventus en la final?",
    category: "Champions League",
    difficulty: "dificil",
    option_a: "Bayern Múnich",
    option_b: "Borussia Dortmund",
    option_c: "Schalke 04",
    option_d: "Werder Bremen",
    correct_answer: "b",
  },
  {
    question: "¿Cuántas Champions League / Copas de Europa ha ganado el AC Milan en su historia?",
    category: "Champions League",
    difficulty: "dificil",
    option_a: "5",
    option_b: "6",
    option_c: "7",
    option_d: "8",
    correct_answer: "c",
  },
  {
    question:
      "¿Qué club ganó la última edición del torneo bajo el nombre 'Copa de Europa', antes de pasar a llamarse 'Champions League' en 1992-93?",
    category: "Champions League",
    difficulty: "dificil",
    option_a: "Barcelona",
    option_b: "Milan",
    option_c: "Estrella Roja",
    option_d: "Marsella",
    correct_answer: "a",
  },
  {
    question: "¿Qué club ha ganado más títulos de la Copa Libertadores en la historia?",
    category: "Libertadores",
    difficulty: "media",
    option_a: "Boca Juniors",
    option_b: "River Plate",
    option_c: "Independiente",
    option_d: "Peñarol",
    correct_answer: "c",
  },
  {
    question: "¿Qué club brasileño fue el primero en ganar la Copa Libertadores, en 1962?",
    category: "Libertadores",
    difficulty: "dificil",
    option_a: "Flamengo",
    option_b: "Santos",
    option_c: "São Paulo",
    option_d: "Palmeiras",
    correct_answer: "b",
  },
  {
    question:
      "¿Qué club colombiano ganó su única Copa Libertadores en 2004, venciendo a Boca Juniors en los penales?",
    category: "Libertadores",
    difficulty: "dificil",
    option_a: "Atlético Nacional",
    option_b: "Millonarios",
    option_c: "Once Caldas",
    option_d: "América de Cali",
    correct_answer: "c",
  },
  {
    question: "¿Qué club ganó la Copa Libertadores 2019 en la final disputada en Lima, Perú?",
    category: "Libertadores",
    difficulty: "media",
    option_a: "Flamengo",
    option_b: "River Plate",
    option_c: "Boca Juniors",
    option_d: "Palmeiras",
    correct_answer: "b",
  },
  {
    question: "¿En qué año ganó Independiente su primera Copa Libertadores?",
    category: "Libertadores",
    difficulty: "dificil",
    option_a: "1960",
    option_b: "1964",
    option_c: "1972",
    option_d: "1984",
    correct_answer: "b",
  },
  {
    question: "¿Qué selección ganó la Eurocopa de 2004 como gran sorpresa del torneo?",
    category: "Eurocopa",
    difficulty: "media",
    option_a: "Portugal",
    option_b: "Grecia",
    option_c: "República Checa",
    option_d: "Países Bajos",
    correct_answer: "b",
  },
  {
    question:
      "¿Qué selección ganó tres torneos internacionales consecutivos: Eurocopa 2008, Mundial 2010 y Eurocopa 2012?",
    category: "Eurocopa",
    difficulty: "dificil",
    option_a: "Alemania",
    option_b: "Italia",
    option_c: "España",
    option_d: "Francia",
    correct_answer: "c",
  },
  {
    question:
      "¿En qué año ganó Argentina la Copa América por última vez antes de su título de 2021, cortando una sequía de 28 años?",
    category: "Copa América",
    difficulty: "dificil",
    option_a: "1991",
    option_b: "1993",
    option_c: "1989",
    option_d: "1995",
    correct_answer: "b",
  },
  {
    question: "¿En qué estadio se jugó la final de la Copa América 2021 entre Argentina y Brasil?",
    category: "Copa América",
    difficulty: "media",
    option_a: "Estadio Monumental",
    option_b: "Maracaná",
    option_c: "La Bombonera",
    option_d: "Centenario",
    correct_answer: "b",
  },
  {
    question: "¿Qué selección ganó la Copa América Centenario 2016, disputada en Estados Unidos?",
    category: "Copa América",
    difficulty: "dificil",
    option_a: "Argentina",
    option_b: "Colombia",
    option_c: "Chile",
    option_d: "Uruguay",
    correct_answer: "c",
  },
  {
    question: "¿Quién ganó el primer Balón de Oro de la historia, en 1956?",
    category: "Individuales",
    difficulty: "dificil",
    option_a: "Alfredo Di Stéfano",
    option_b: "Stanley Matthews",
    option_c: "Raymond Kopa",
    option_d: "Lev Yashin",
    correct_answer: "b",
  },
  {
    question: "¿Qué jugador africano ganó el Balón de Oro en 1995, siendo hasta hoy el único africano en lograrlo?",
    category: "Individuales",
    difficulty: "dificil",
    option_a: "Samuel Eto'o",
    option_b: "Didier Drogba",
    option_c: "George Weah",
    option_d: "Yaya Touré",
    correct_answer: "c",
  },
  {
    question: "¿Qué jugador tiene el récord de más Botas de Oro europeas (mejor goleador de Europa) de la historia?",
    category: "Individuales",
    difficulty: "dificil",
    option_a: "4",
    option_b: "5",
    option_c: "6",
    option_d: "7",
    correct_answer: "c",
  },
  {
    question: "¿Quién ganó el primer Balón de Oro femenino de la historia, en 2018?",
    category: "Individuales",
    difficulty: "dificil",
    option_a: "Alex Morgan",
    option_b: "Ada Hegerberg",
    option_c: "Marta",
    option_d: "Megan Rapinoe",
    correct_answer: "b",
  },
  {
    question: "¿En qué año se fundó la FIFA?",
    category: "Historia",
    difficulty: "dificil",
    option_a: "1904",
    option_b: "1920",
    option_c: "1888",
    option_d: "1930",
    correct_answer: "a",
  },
  {
    question: "¿En qué año se fundó el Madrid Football Club, actual Real Madrid?",
    category: "Historia",
    difficulty: "dificil",
    option_a: "1898",
    option_b: "1902",
    option_c: "1910",
    option_d: "1920",
    correct_answer: "b",
  },
  {
    question:
      "¿A qué club pertenecían los 'Busby Babes', varios de los cuales murieron en la tragedia aérea de Múnich en 1958?",
    category: "Historia",
    difficulty: "dificil",
    option_a: "Manchester City",
    option_b: "Manchester United",
    option_c: "Liverpool",
    option_d: "Arsenal",
    correct_answer: "b",
  },
  {
    question:
      "¿En qué año ocurrió la tragedia de Heysel, que derivó en la prohibición de los clubes ingleses en competiciones europeas?",
    category: "Historia",
    difficulty: "dificil",
    option_a: "1980",
    option_b: "1985",
    option_c: "1990",
    option_d: "1975",
    correct_answer: "b",
  },
  {
    question:
      "¿Qué selección, campeona del primer Mundial en 1930, decidió no participar en las ediciones de 1934 y 1938?",
    category: "Historia",
    difficulty: "dificil",
    option_a: "Argentina",
    option_b: "Uruguay",
    option_c: "Brasil",
    option_d: "Paraguay",
    correct_answer: "b",
  },
  {
    question: "¿Qué club neerlandés ganó tres Copas de Europa consecutivas entre 1971 y 1973?",
    category: "Champions League",
    difficulty: "dificil",
    option_a: "Feyenoord",
    option_b: "PSV",
    option_c: "Ajax",
    option_d: "AZ Alkmaar",
    correct_answer: "c",
  },
  {
    question: "¿Qué selección ganó el Mundial de 1934, disputado en Italia?",
    category: "Mundiales",
    difficulty: "media",
    option_a: "Italia",
    option_b: "Checoslovaquia",
    option_c: "Austria",
    option_d: "Hungría",
    correct_answer: "a",
  },
  {
    question: "¿Qué selección revalidó el título mundial en la edición de 1938, disputada en Francia?",
    category: "Mundiales",
    difficulty: "dificil",
    option_a: "Brasil",
    option_b: "Hungría",
    option_c: "Italia",
    option_d: "Alemania",
    correct_answer: "c",
  },
  {
    question: "¿Cuántos Mundiales ha ganado Brasil en total, la selección con más títulos?",
    category: "Mundiales",
    difficulty: "media",
    option_a: "4",
    option_b: "5",
    option_c: "6",
    option_d: "3",
    correct_answer: "b",
  },
  {
    question: "¿Qué arquero ganó el Guante de Oro al mejor portero del Mundial de Rusia 2018?",
    category: "Individuales",
    difficulty: "dificil",
    option_a: "Hugo Lloris",
    option_b: "Thibaut Courtois",
    option_c: "David de Gea",
    option_d: "Jan Oblak",
    correct_answer: "b",
  },
  {
    question: "¿Qué club brasileño ganó el primer Mundial de Clubes de la FIFA, disputado en el año 2000?",
    category: "Historia",
    difficulty: "dificil",
    option_a: "São Paulo",
    option_b: "Vasco da Gama",
    option_c: "Corinthians",
    option_d: "Palmeiras",
    correct_answer: "c",
  },
  {
    question: "¿Qué selección ganó la Eurocopa 2020, disputada en 2021 por la pandemia?",
    category: "Eurocopa",
    difficulty: "media",
    option_a: "Inglaterra",
    option_b: "Italia",
    option_c: "España",
    option_d: "Bélgica",
    correct_answer: "b",
  },
  {
    question:
      "¿Cuántos goles convirtió Diego Maradona en el Mundial de México 1986, torneo en el que ganó el Balón de Oro?",
    category: "Individuales",
    difficulty: "dificil",
    option_a: "4",
    option_b: "5",
    option_c: "6",
    option_d: "7",
    correct_answer: "b",
  },
  {
    question: "¿Qué club uruguayo, además de Peñarol, ganó la Copa Libertadores en tres ocasiones?",
    category: "Libertadores",
    difficulty: "dificil",
    option_a: "Danubio",
    option_b: "Nacional",
    option_c: "Defensor Sporting",
    option_d: "Wanderers",
    correct_answer: "b",
  },
  {
    question: "¿En qué estadio se jugó la final del Mundial de 1950, escenario del 'Maracanazo'?",
    category: "Mundiales",
    difficulty: "media",
    option_a: "Estadio Centenario",
    option_b: "Maracaná",
    option_c: "Monumental",
    option_d: "La Bombonera",
    correct_answer: "b",
  },
  {
    question: "¿Qué selección ganó el Mundial de 1986, disputado en México?",
    category: "Mundiales",
    difficulty: "media",
    option_a: "Alemania Occidental",
    option_b: "Argentina",
    option_c: "Brasil",
    option_d: "Italia",
    correct_answer: "b",
  },
  {
    question:
      "¿Qué jugador italiano ganó el primer Balón de Oro del Mundial (premio al mejor jugador del torneo), en 1982?",
    category: "Individuales",
    difficulty: "dificil",
    option_a: "Paolo Rossi",
    option_b: "Marco Tardelli",
    option_c: "Dino Zoff",
    option_d: "Bruno Conti",
    correct_answer: "a",
  },
];

const QUESTIONS_PER_DAY = 3;

async function seed() {
  await initSchema();

  for (let i = 0; i < QUESTIONS.length; i++) {
    const q = QUESTIONS[i];
    const day = Math.floor(i / QUESTIONS_PER_DAY);
    const slot = (i % QUESTIONS_PER_DAY) + 1;
    const scheduled_date = dateOffset(day);

    const updateResult = await db.execute({
      sql: `UPDATE questions SET
              question = ?, category = ?, difficulty = ?,
              option_a = ?, option_b = ?, option_c = ?, option_d = ?, correct_answer = ?
            WHERE scheduled_date = ? AND slot = ?`,
      args: [
        q.question,
        q.category,
        q.difficulty,
        q.option_a,
        q.option_b,
        q.option_c,
        q.option_d,
        q.correct_answer,
        scheduled_date,
        slot,
      ],
    });

    if (updateResult.rowsAffected === 0) {
      await db.execute({
        sql: `INSERT INTO questions
          (question, category, difficulty, option_a, option_b, option_c, option_d, correct_answer, scheduled_date, slot)
          VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        args: [
          q.question,
          q.category,
          q.difficulty,
          q.option_a,
          q.option_b,
          q.option_c,
          q.option_d,
          q.correct_answer,
          scheduled_date,
          slot,
        ],
      });
    }
  }

  const days = Math.ceil(QUESTIONS.length / QUESTIONS_PER_DAY);
  console.log(
    `Seed completado: ${QUESTIONS.length} preguntas sincronizadas (${QUESTIONS_PER_DAY}/día, ${days} días de cobertura).`
  );
  process.exit(0);
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
